name = "primary-english-api-gateway-dev"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

# 主要函數入口
main = "functions/api-gateway.js"

# 本地開發配置
[dev]
port = 8787
local = true

# 環境變數
[vars]
ENVIRONMENT = "development"
API_SECRET = "local-dev-secret"

# D1 資料庫綁定（本地開發）
[[d1_databases]]
binding = "PRIMARY_ENGLISH_DB"
database_name = "primary-english-db"
database_id = "203cdead-8e8a-4c1d-a77b-9c5445e4f5f8"

# R2 存儲綁定（本地開發）
[[r2_buckets]]
binding = "primary_english_storage"
bucket_name = "primary-english-storage"
