name = "primary-english-api-gateway"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

# 主要函數入口
main = "functions/api-gateway.js"

# 環境變數
[vars]
ENVIRONMENT = "production"

# D1 資料庫綁定
[[d1_databases]]
binding = "PRIMARY_ENGLISH_DB"
database_name = "primary-english-db"
database_id = "203cdead-8e8a-4c1d-a77b-9c5445e4f5f8"

# R2 存儲綁定
[[r2_buckets]]
binding = "primary_english_storage"
bucket_name = "primary-english-storage"

# 環境變數（需要在 Cloudflare 後台設定）
# API_SECRET 用於驗證來自 Vercel 的請求
# 這個值需要在 Cloudflare Workers 的環境變數中設定
