import { NextRequest, NextResponse } from "next/server";
import {
  LearningContentResponse,
  WordsByThemeResponse,
  SentencePatternsResponse,
  ThemesResponse,
  QuestionAnswerPairsResponse,
  WordTheme,
  Word,
} from "@/types/learning-content";

// Mock data for development (replace with actual D1 queries)
// IMPORTANT: These IDs must match the D1 database schema exactly
const mockGrades = [
  { id: 1, name: "Grade 3" }, // grade_id: 1 in D1 = Grade 3
  { id: 2, name: "Grade 5" }, // grade_id: 2 in D1 = Grade 5
  { id: 3, name: "Grade 6" }, // grade_id: 3 in D1 = Grade 6
];

// Mock word themes
const mockThemes: WordTheme[] = [
  { id: 1, name: "Emotions" },
  { id: 2, name: "Colors" },
  { id: 3, name: "Sports" },
  { id: 4, name: "Stationery" },
  { id: 5, name: "Fruits" },
  { id: 6, name: "Fast Food" },
  { id: 7, name: "Bakery & Snacks" },
  { id: 8, name: "Days of Week" },
  { id: 9, name: "Months" },
  { id: 10, name: "School Subjects" },
  { id: 11, name: "Ailments" },
  { id: 12, name: "Countries" },
  { id: 13, name: "Furniture" },
  { id: 14, name: "Toys" },
  { id: 15, name: "Drinks" },
  { id: 16, name: "Main Dishes" },
  { id: 17, name: "Bubble Tea Toppings" },
  { id: 18, name: "Identity" },
  { id: 19, name: "Professions" },
  { id: 20, name: "Daily Actions" },
  { id: 21, name: "Clothing" },
  { id: 22, name: "Buildings & Places" },
  { id: 23, name: "Numbers" },
  { id: 24, name: "Time Expressions" },
];

// Mock words with has_plural field
const mockWords: Word[] = [
  // Emotions (adjective) - no plurals
  {
    id: 1,
    english_singular: "happy",
    english_plural: undefined,
    chinese_meaning: "開心的",
    part_of_speech: "adjective",
    has_plural: false,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 2,
    english_singular: "sad",
    english_plural: undefined,
    chinese_meaning: "傷心的",
    part_of_speech: "adjective",
    has_plural: false,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 3,
    english_singular: "angry",
    english_plural: undefined,
    chinese_meaning: "生氣的",
    part_of_speech: "adjective",
    has_plural: false,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 4,
    english_singular: "tired",
    english_plural: undefined,
    chinese_meaning: "疲倦的",
    part_of_speech: "adjective",
    has_plural: false,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 5,
    english_singular: "excited",
    english_plural: undefined,
    chinese_meaning: "興奮的",
    part_of_speech: "adjective",
    has_plural: false,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 6,
    english_singular: "bored",
    english_plural: undefined,
    chinese_meaning: "無聊的",
    part_of_speech: "adjective",
    has_plural: false,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 7,
    english_singular: "surprised",
    english_plural: undefined,
    chinese_meaning: "驚訝的",
    part_of_speech: "adjective",
    has_plural: false,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 8,
    english_singular: "scared",
    english_plural: undefined,
    chinese_meaning: "害怕的",
    part_of_speech: "adjective",
    has_plural: false,
    image_url: undefined,
    audio_url: undefined,
  },

  // Colors (adjective) - no plurals
  {
    id: 9,
    english_singular: "red",
    english_plural: undefined,
    chinese_meaning: "紅色",
    part_of_speech: "adjective",
    has_plural: false,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 10,
    english_singular: "blue",
    english_plural: undefined,
    chinese_meaning: "藍色",
    part_of_speech: "adjective",
    has_plural: false,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 11,
    english_singular: "yellow",
    english_plural: undefined,
    chinese_meaning: "黃色",
    part_of_speech: "adjective",
    has_plural: false,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 12,
    english_singular: "green",
    english_plural: undefined,
    chinese_meaning: "綠色",
    part_of_speech: "adjective",
    has_plural: false,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 13,
    english_singular: "black",
    english_plural: undefined,
    chinese_meaning: "黑色",
    part_of_speech: "adjective",
    has_plural: false,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 14,
    english_singular: "white",
    english_plural: undefined,
    chinese_meaning: "白色",
    part_of_speech: "adjective",
    has_plural: false,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 15,
    english_singular: "pink",
    english_plural: undefined,
    chinese_meaning: "粉紅色",
    part_of_speech: "adjective",
    has_plural: false,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 16,
    english_singular: "purple",
    english_plural: undefined,
    chinese_meaning: "紫色",
    part_of_speech: "adjective",
    has_plural: false,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 17,
    english_singular: "orange",
    english_plural: undefined,
    chinese_meaning: "橘色",
    part_of_speech: "adjective",
    has_plural: false,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 18,
    english_singular: "brown",
    english_plural: undefined,
    chinese_meaning: "棕色",
    part_of_speech: "adjective",
    has_plural: false,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 19,
    english_singular: "gray",
    english_plural: undefined,
    chinese_meaning: "灰色",
    part_of_speech: "adjective",
    has_plural: false,
    image_url: undefined,
    audio_url: undefined,
  },

  // Sports (noun) - some have plurals
  {
    id: 20,
    english_singular: "basketball",
    english_plural: "basketballs",
    chinese_meaning: "籃球",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 21,
    english_singular: "soccer",
    english_plural: undefined,
    chinese_meaning: "足球",
    part_of_speech: "noun",
    has_plural: false,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 22,
    english_singular: "baseball",
    english_plural: "baseballs",
    chinese_meaning: "棒球",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 23,
    english_singular: "tennis",
    english_plural: undefined,
    chinese_meaning: "網球",
    part_of_speech: "noun",
    has_plural: false,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 24,
    english_singular: "badminton",
    english_plural: undefined,
    chinese_meaning: "羽毛球",
    part_of_speech: "noun",
    has_plural: false,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 25,
    english_singular: "swimming",
    english_plural: undefined,
    chinese_meaning: "游泳",
    part_of_speech: "noun",
    has_plural: false,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 26,
    english_singular: "running",
    english_plural: undefined,
    chinese_meaning: "跑步",
    part_of_speech: "noun",
    has_plural: false,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 27,
    english_singular: "jogging",
    english_plural: undefined,
    chinese_meaning: "慢跑",
    part_of_speech: "noun",
    has_plural: false,
    image_url: undefined,
    audio_url: undefined,
  },

  // Stationery (noun) - all have plurals
  {
    id: 28,
    english_singular: "pen",
    english_plural: "pens",
    chinese_meaning: "筆",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 29,
    english_singular: "pencil",
    english_plural: "pencils",
    chinese_meaning: "鉛筆",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 30,
    english_singular: "eraser",
    english_plural: "erasers",
    chinese_meaning: "橡皮擦",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 31,
    english_singular: "ruler",
    english_plural: "rulers",
    chinese_meaning: "尺",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 32,
    english_singular: "book",
    english_plural: "books",
    chinese_meaning: "書",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 33,
    english_singular: "notebook",
    english_plural: "notebooks",
    chinese_meaning: "筆記本",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 34,
    english_singular: "marker",
    english_plural: "markers",
    chinese_meaning: "麥克筆",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },

  // Fruits (noun) - all have plurals
  {
    id: 35,
    english_singular: "apple",
    english_plural: "apples",
    chinese_meaning: "蘋果",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 36,
    english_singular: "banana",
    english_plural: "bananas",
    chinese_meaning: "香蕉",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 37,
    english_singular: "orange",
    english_plural: "oranges",
    chinese_meaning: "橘子",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 38,
    english_singular: "grape",
    english_plural: "grapes",
    chinese_meaning: "葡萄",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 39,
    english_singular: "guava",
    english_plural: "guavas",
    chinese_meaning: "芭樂",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 40,
    english_singular: "lemon",
    english_plural: "lemons",
    chinese_meaning: "檸檬",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 41,
    english_singular: "strawberry",
    english_plural: "strawberries",
    chinese_meaning: "草莓",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },

  // Fast Food (noun) - some have plurals
  {
    id: 42,
    english_singular: "hamburger",
    english_plural: "hamburgers",
    chinese_meaning: "漢堡",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 43,
    english_singular: "fries",
    english_plural: undefined,
    chinese_meaning: "薯條",
    part_of_speech: "noun",
    has_plural: false,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 44,
    english_singular: "pizza",
    english_plural: "pizzas",
    chinese_meaning: "披薩",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 45,
    english_singular: "hot dog",
    english_plural: "hot dogs",
    chinese_meaning: "熱狗",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 46,
    english_singular: "chicken nugget",
    english_plural: "chicken nuggets",
    chinese_meaning: "雞塊",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 47,
    english_singular: "soda",
    english_plural: "sodas",
    chinese_meaning: "汽水",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },

  // Bakery & Snacks (noun) - some have plurals
  {
    id: 48,
    english_singular: "bread",
    english_plural: undefined,
    chinese_meaning: "麵包",
    part_of_speech: "noun",
    has_plural: false,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 49,
    english_singular: "cake",
    english_plural: "cakes",
    chinese_meaning: "蛋糕",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 50,
    english_singular: "cookie",
    english_plural: "cookies",
    chinese_meaning: "餅乾",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 51,
    english_singular: "donut",
    english_plural: "donuts",
    chinese_meaning: "甜甜圈",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 52,
    english_singular: "pie",
    english_plural: "pies",
    chinese_meaning: "派",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 53,
    english_singular: "candy",
    english_plural: "candies",
    chinese_meaning: "糖果",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 100,
    english_singular: "wrong",
    english_plural: undefined,
    chinese_meaning: "錯誤的",
    part_of_speech: "adjective",
    has_plural: false,
  },
  {
    id: 101,
    english_singular: "favorite",
    english_plural: undefined,
    chinese_meaning: "最喜歡的",
    part_of_speech: "adjective",
    has_plural: false,
  },

  // Identity words (Theme 18)
  {
    id: 102,
    english_singular: "student",
    english_plural: "students",
    chinese_meaning: "學生",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 103,
    english_singular: "teacher",
    english_plural: "teachers",
    chinese_meaning: "老師",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 104,
    english_singular: "friend",
    english_plural: "friends",
    chinese_meaning: "朋友",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 105,
    english_singular: "classmate",
    english_plural: "classmates",
    chinese_meaning: "同學",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 106,
    english_singular: "family",
    english_plural: "families",
    chinese_meaning: "家人",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 107,
    english_singular: "parent",
    english_plural: "parents",
    chinese_meaning: "父母",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 108,
    english_singular: "child",
    english_plural: "children",
    chinese_meaning: "小孩",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 109,
    english_singular: "sister",
    english_plural: "sisters",
    chinese_meaning: "姐妹",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 110,
    english_singular: "brother",
    english_plural: "brothers",
    chinese_meaning: "兄弟",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 111,
    english_singular: "cousin",
    english_plural: "cousins",
    chinese_meaning: "堂/表兄弟姊妹",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },

  // Professions words (Theme 19) - Expanded list
  {
    id: 112,
    english_singular: "doctor",
    english_plural: "doctors",
    chinese_meaning: "醫生",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 113,
    english_singular: "nurse",
    english_plural: "nurses",
    chinese_meaning: "護士",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 114,
    english_singular: "engineer",
    english_plural: "engineers",
    chinese_meaning: "工程師",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 115,
    english_singular: "artist",
    english_plural: "artists",
    chinese_meaning: "藝術家",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 116,
    english_singular: "chef",
    english_plural: "chefs",
    chinese_meaning: "廚師",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 117,
    english_singular: "driver",
    english_plural: "drivers",
    chinese_meaning: "司機",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 118,
    english_singular: "police officer",
    english_plural: "police officers",
    chinese_meaning: "警察",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 119,
    english_singular: "firefighter",
    english_plural: "firefighters",
    chinese_meaning: "消防員",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 120,
    english_singular: "scientist",
    english_plural: "scientists",
    chinese_meaning: "科學家",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 121,
    english_singular: "musician",
    english_plural: "musicians",
    chinese_meaning: "音樂家",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 122,
    english_singular: "dentist",
    english_plural: "dentists",
    chinese_meaning: "牙醫",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 123,
    english_singular: "lawyer",
    english_plural: "lawyers",
    chinese_meaning: "律師",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 124,
    english_singular: "architect",
    english_plural: "architects",
    chinese_meaning: "建築師",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 125,
    english_singular: "designer",
    english_plural: "designers",
    chinese_meaning: "設計師",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 126,
    english_singular: "photographer",
    english_plural: "photographers",
    chinese_meaning: "攝影師",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 127,
    english_singular: "journalist",
    english_plural: "journalists",
    chinese_meaning: "記者",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 128,
    english_singular: "accountant",
    english_plural: "accountants",
    chinese_meaning: "會計師",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 129,
    english_singular: "salesperson",
    english_plural: "salespeople",
    chinese_meaning: "銷售員",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 130,
    english_singular: "waiter",
    english_plural: "waiters",
    chinese_meaning: "服務生",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 131,
    english_singular: "waitress",
    english_plural: "waitresses",
    chinese_meaning: "女服務生",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 132,
    english_singular: "pilot",
    english_plural: "pilots",
    chinese_meaning: "飛行員",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 133,
    english_singular: "sailor",
    english_plural: "sailors",
    chinese_meaning: "水手",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 134,
    english_singular: "farmer",
    english_plural: "farmers",
    chinese_meaning: "農夫",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 135,
    english_singular: "fisherman",
    english_plural: "fishermen",
    chinese_meaning: "漁夫",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 136,
    english_singular: "carpenter",
    english_plural: "carpenters",
    chinese_meaning: "木匠",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 137,
    english_singular: "plumber",
    english_plural: "plumbers",
    chinese_meaning: "水管工",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 138,
    english_singular: "electrician",
    english_plural: "electricians",
    chinese_meaning: "電工",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 139,
    english_singular: "mechanic",
    english_plural: "mechanics",
    chinese_meaning: "技工",
    part_of_speech: "noun",
    has_plural: true,
  },

  // Additional Colors as nouns (Theme 2) - expanding the theme
  {
    id: 200,
    english_singular: "red color",
    english_plural: "red colors",
    chinese_meaning: "紅色",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 201,
    english_singular: "blue color",
    english_plural: "blue colors",
    chinese_meaning: "藍色",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 202,
    english_singular: "yellow color",
    english_plural: "yellow colors",
    chinese_meaning: "黃色",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 203,
    english_singular: "green color",
    english_plural: "green colors",
    chinese_meaning: "綠色",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 204,
    english_singular: "black color",
    english_plural: "black colors",
    chinese_meaning: "黑色",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 205,
    english_singular: "white color",
    english_plural: "white colors",
    chinese_meaning: "白色",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 206,
    english_singular: "pink color",
    english_plural: "pink colors",
    chinese_meaning: "粉紅色",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 207,
    english_singular: "purple color",
    english_plural: "purple colors",
    chinese_meaning: "紫色",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 208,
    english_singular: "orange color",
    english_plural: "orange colors",
    chinese_meaning: "橘色",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 209,
    english_singular: "brown color",
    english_plural: "brown colors",
    chinese_meaning: "棕色",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },

  // Daily Actions words (Theme 20) - Everyday activities and routines
  {
    id: 140,
    english_singular: "wake up",
    english_plural: undefined,
    chinese_meaning: "起床",
    part_of_speech: "verb",
    has_plural: false,
  },
  {
    id: 141,
    english_singular: "get up",
    english_plural: undefined,
    chinese_meaning: "起床",
    part_of_speech: "verb",
    has_plural: false,
  },
  {
    id: 142,
    english_singular: "brush teeth",
    english_plural: undefined,
    chinese_meaning: "刷牙",
    part_of_speech: "verb",
    has_plural: false,
  },
  {
    id: 143,
    english_singular: "wash face",
    english_plural: undefined,
    chinese_meaning: "洗臉",
    part_of_speech: "verb",
    has_plural: false,
  },
  {
    id: 144,
    english_singular: "take a shower",
    english_plural: "take showers",
    chinese_meaning: "洗澡",
    part_of_speech: "verb",
    has_plural: true,
  },
  {
    id: 145,
    english_singular: "eat breakfast",
    english_plural: "eat breakfasts",
    chinese_meaning: "吃早餐",
    part_of_speech: "verb",
    has_plural: true,
  },
  {
    id: 146,
    english_singular: "go to school",
    english_plural: undefined,
    chinese_meaning: "上學",
    part_of_speech: "verb",
    has_plural: false,
  },
  {
    id: 147,
    english_singular: "study",
    english_plural: "studies",
    chinese_meaning: "讀書",
    part_of_speech: "verb",
    has_plural: true,
  },
  {
    id: 148,
    english_singular: "read",
    english_plural: "reads",
    chinese_meaning: "閱讀",
    part_of_speech: "verb",
    has_plural: true,
  },
  {
    id: 149,
    english_singular: "write",
    english_plural: "writes",
    chinese_meaning: "寫字",
    part_of_speech: "verb",
    has_plural: true,
  },
  {
    id: 150,
    english_singular: "listen",
    english_plural: "listens",
    chinese_meaning: "聽",
    part_of_speech: "verb",
    has_plural: true,
  },
  {
    id: 151,
    english_singular: "speak",
    english_plural: "speaks",
    chinese_meaning: "說話",
    part_of_speech: "verb",
    has_plural: true,
  },
  {
    id: 152,
    english_singular: "cook",
    english_plural: "cooks",
    chinese_meaning: "煮飯",
    part_of_speech: "verb",
    has_plural: true,
  },
  {
    id: 153,
    english_singular: "clean",
    english_plural: "cleans",
    chinese_meaning: "打掃",
    part_of_speech: "verb",
    has_plural: true,
  },
  {
    id: 154,
    english_singular: "sleep",
    english_plural: "sleeps",
    chinese_meaning: "睡覺",
    part_of_speech: "verb",
    has_plural: true,
  },
  {
    id: 155,
    english_singular: "work",
    english_plural: "works",
    chinese_meaning: "工作",
    part_of_speech: "verb",
    has_plural: true,
  },
  {
    id: 156,
    english_singular: "play",
    english_plural: "plays",
    chinese_meaning: "玩",
    part_of_speech: "verb",
    has_plural: true,
  },
  {
    id: 157,
    english_singular: "watch TV",
    english_plural: undefined,
    chinese_meaning: "看電視",
    part_of_speech: "verb",
    has_plural: false,
  },
  {
    id: 158,
    english_singular: "drive",
    english_plural: "drives",
    chinese_meaning: "開車",
    part_of_speech: "verb",
    has_plural: true,
  },
  {
    id: 159,
    english_singular: "walk",
    english_plural: "walks",
    chinese_meaning: "走路",
    part_of_speech: "verb",
    has_plural: true,
  },

  // 新增休閒娛樂活動 (Theme 20)
  {
    id: 160,
    english_singular: "watch a movie",
    english_plural: "watch movies",
    chinese_meaning: "看電影",
    part_of_speech: "verb",
    has_plural: true,
  },
  {
    id: 161,
    english_singular: "go to the movies",
    english_plural: undefined,
    chinese_meaning: "去看電影",
    part_of_speech: "verb",
    has_plural: false,
  },
  {
    id: 162,
    english_singular: "play video games",
    english_plural: undefined,
    chinese_meaning: "玩電動",
    part_of_speech: "verb",
    has_plural: false,
  },
  {
    id: 163,
    english_singular: "play board games",
    english_plural: undefined,
    chinese_meaning: "玩桌遊",
    part_of_speech: "verb",
    has_plural: false,
  },
  {
    id: 164,
    english_singular: "go shopping",
    english_plural: undefined,
    chinese_meaning: "購物",
    part_of_speech: "verb",
    has_plural: false,
  },
  {
    id: 165,
    english_singular: "go swimming",
    english_plural: undefined,
    chinese_meaning: "游泳",
    part_of_speech: "verb",
    has_plural: false,
  },
  {
    id: 166,
    english_singular: "go hiking",
    english_plural: undefined,
    chinese_meaning: "健行",
    part_of_speech: "verb",
    has_plural: false,
  },
  {
    id: 167,
    english_singular: "go camping",
    english_plural: undefined,
    chinese_meaning: "露營",
    part_of_speech: "verb",
    has_plural: false,
  },
  {
    id: 168,
    english_singular: "go fishing",
    english_plural: undefined,
    chinese_meaning: "釣魚",
    part_of_speech: "verb",
    has_plural: false,
  },
  {
    id: 169,
    english_singular: "go dancing",
    english_plural: undefined,
    chinese_meaning: "跳舞",
    part_of_speech: "verb",
    has_plural: false,
  },
  {
    id: 170,
    english_singular: "go singing",
    english_plural: undefined,
    chinese_meaning: "唱歌",
    part_of_speech: "verb",
    has_plural: false,
  },
  {
    id: 171,
    english_singular: "go painting",
    english_plural: undefined,
    chinese_meaning: "畫畫",
    part_of_speech: "verb",
    has_plural: false,
  },
  {
    id: 172,
    english_singular: "go drawing",
    english_plural: undefined,
    chinese_meaning: "素描",
    part_of_speech: "verb",
    has_plural: false,
  },
  {
    id: 173,
    english_singular: "go gardening",
    english_plural: undefined,
    chinese_meaning: "園藝",
    part_of_speech: "verb",
    has_plural: false,
  },
  {
    id: 174,
    english_singular: "go cycling",
    english_plural: undefined,
    chinese_meaning: "騎腳踏車",
    part_of_speech: "verb",
    has_plural: false,
  },
  {
    id: 175,
    english_singular: "go running",
    english_plural: undefined,
    chinese_meaning: "跑步",
    part_of_speech: "verb",
    has_plural: false,
  },

  // Clothing words (Theme 21) - Different types of clothing and accessories
  {
    id: 176,
    english_singular: "shirt",
    english_plural: "shirts",
    chinese_meaning: "襯衫",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 177,
    english_singular: "pants",
    english_plural: undefined,
    chinese_meaning: "褲子",
    part_of_speech: "noun",
    has_plural: false,
  },
  {
    id: 178,
    english_singular: "dress",
    english_plural: "dresses",
    chinese_meaning: "洋裝",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 179,
    english_singular: "skirt",
    english_plural: "skirts",
    chinese_meaning: "裙子",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 180,
    english_singular: "jacket",
    english_plural: "jackets",
    chinese_meaning: "外套",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 181,
    english_singular: "coat",
    english_plural: "coats",
    chinese_meaning: "大衣",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 182,
    english_singular: "sweater",
    english_plural: "sweaters",
    chinese_meaning: "毛衣",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 183,
    english_singular: "hat",
    english_plural: "hats",
    chinese_meaning: "帽子",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 184,
    english_singular: "cap",
    english_plural: "caps",
    chinese_meaning: "棒球帽",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 185,
    english_singular: "shoes",
    english_plural: undefined,
    chinese_meaning: "鞋子",
    part_of_speech: "noun",
    has_plural: false,
  },
  {
    id: 186,
    english_singular: "sneakers",
    english_plural: undefined,
    chinese_meaning: "運動鞋",
    part_of_speech: "noun",
    has_plural: false,
  },
  {
    id: 187,
    english_singular: "boots",
    english_plural: undefined,
    chinese_meaning: "靴子",
    part_of_speech: "noun",
    has_plural: false,
  },
  {
    id: 188,
    english_singular: "socks",
    english_plural: undefined,
    chinese_meaning: "襪子",
    part_of_speech: "noun",
    has_plural: false,
  },
  {
    id: 189,
    english_singular: "underwear",
    english_plural: undefined,
    chinese_meaning: "內衣",
    part_of_speech: "noun",
    has_plural: false,
  },
  {
    id: 190,
    english_singular: "belt",
    english_plural: "belts",
    chinese_meaning: "皮帶",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 191,
    english_singular: "scarf",
    english_plural: "scarves",
    chinese_meaning: "圍巾",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 192,
    english_singular: "gloves",
    english_plural: undefined,
    chinese_meaning: "手套",
    part_of_speech: "noun",
    has_plural: false,
  },
  {
    id: 193,
    english_singular: "bag",
    english_plural: "bags",
    chinese_meaning: "包包",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 194,
    english_singular: "backpack",
    english_plural: "backpacks",
    chinese_meaning: "背包",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 195,
    english_singular: "wallet",
    english_plural: "wallets",
    chinese_meaning: "錢包",
    part_of_speech: "noun",
    has_plural: true,
  },

  // Buildings & Places words (Theme 22) - Buildings, stores, and places in the city
  {
    id: 196,
    english_singular: "school",
    english_plural: "schools",
    chinese_meaning: "學校",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 197,
    english_singular: "hospital",
    english_plural: "hospitals",
    chinese_meaning: "醫院",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 198,
    english_singular: "library",
    english_plural: "libraries",
    chinese_meaning: "圖書館",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 199,
    english_singular: "bank",
    english_plural: "banks",
    chinese_meaning: "銀行",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 200,
    english_singular: "post office",
    english_plural: "post offices",
    chinese_meaning: "郵局",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 201,
    english_singular: "police station",
    english_plural: "police stations",
    chinese_meaning: "警察局",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 202,
    english_singular: "fire station",
    english_plural: "fire stations",
    chinese_meaning: "消防局",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 203,
    english_singular: "restaurant",
    english_plural: "restaurants",
    chinese_meaning: "餐廳",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 204,
    english_singular: "cafe",
    english_plural: "cafes",
    chinese_meaning: "咖啡廳",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 205,
    english_singular: "supermarket",
    english_plural: "supermarkets",
    chinese_meaning: "超市",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 206,
    english_singular: "store",
    english_plural: "stores",
    chinese_meaning: "商店",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 207,
    english_singular: "shop",
    english_plural: "shops",
    chinese_meaning: "商店",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 208,
    english_singular: "market",
    english_plural: "markets",
    chinese_meaning: "市場",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 209,
    english_singular: "pharmacy",
    english_plural: "pharmacies",
    chinese_meaning: "藥局",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 210,
    english_singular: "gas station",
    english_plural: "gas stations",
    chinese_meaning: "加油站",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 211,
    english_singular: "bus stop",
    english_plural: "bus stops",
    chinese_meaning: "公車站",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 212,
    english_singular: "train station",
    english_plural: "train stations",
    chinese_meaning: "火車站",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 213,
    english_singular: "airport",
    english_plural: "airports",
    chinese_meaning: "機場",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 214,
    english_singular: "park",
    english_plural: "parks",
    chinese_meaning: "公園",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 215,
    english_singular: "museum",
    english_plural: "museums",
    chinese_meaning: "博物館",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 216,
    english_singular: "cinema",
    english_plural: "cinemas",
    chinese_meaning: "電影院",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 217,
    english_singular: "theater",
    english_plural: "theaters",
    chinese_meaning: "劇院",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 218,
    english_singular: "hotel",
    english_plural: "hotels",
    chinese_meaning: "旅館",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 219,
    english_singular: "office",
    english_plural: "offices",
    chinese_meaning: "辦公室",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 219,
    english_singular: "house",
    english_plural: "houses",
    chinese_meaning: "房子",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 220,
    english_singular: "apartment",
    english_plural: "apartments",
    chinese_meaning: "公寓",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 221,
    english_singular: "building",
    english_plural: "buildings",
    chinese_meaning: "建築物",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 222,
    english_singular: "street",
    english_plural: "streets",
    chinese_meaning: "街道",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 223,
    english_singular: "road",
    english_plural: "roads",
    chinese_meaning: "道路",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 224,
    english_singular: "bridge",
    english_plural: "bridges",
    chinese_meaning: "橋樑",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 225,
    english_singular: "tower",
    english_plural: "towers",
    chinese_meaning: "塔",
    part_of_speech: "noun",
    has_plural: true,
  },

  // Furniture words (Theme 13) - all have plurals
  {
    id: 42,
    english_singular: "chair",
    english_plural: "chairs",
    chinese_meaning: "椅子",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 43,
    english_singular: "table",
    english_plural: "tables",
    chinese_meaning: "桌子",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 44,
    english_singular: "bed",
    english_plural: "beds",
    chinese_meaning: "床",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 45,
    english_singular: "desk",
    english_plural: "desks",
    chinese_meaning: "書桌",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 46,
    english_singular: "sofa",
    english_plural: "sofas",
    chinese_meaning: "沙發",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 47,
    english_singular: "lamp",
    english_plural: "lamps",
    chinese_meaning: "檯燈",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },

  // Drinks words (Theme 15) - most are uncountable
  {
    id: 48,
    english_singular: "water",
    english_plural: undefined,
    chinese_meaning: "水",
    part_of_speech: "noun",
    has_plural: false,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 49,
    english_singular: "milk",
    english_plural: undefined,
    chinese_meaning: "牛奶",
    part_of_speech: "noun",
    has_plural: false,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 50,
    english_singular: "juice",
    english_plural: undefined,
    chinese_meaning: "果汁",
    part_of_speech: "noun",
    has_plural: false,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 51,
    english_singular: "tea",
    english_plural: undefined,
    chinese_meaning: "茶",
    part_of_speech: "noun",
    has_plural: false,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 52,
    english_singular: "coffee",
    english_plural: undefined,
    chinese_meaning: "咖啡",
    part_of_speech: "noun",
    has_plural: false,
    image_url: undefined,
    audio_url: undefined,
  },

  // Fast Food (noun) - some have plurals
  {
    id: 54,
    english_singular: "hamburger",
    english_plural: "hamburgers",
    chinese_meaning: "漢堡",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 55,
    english_singular: "fries",
    english_plural: undefined,
    chinese_meaning: "薯條",
    part_of_speech: "noun",
    has_plural: false,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 56,
    english_singular: "pizza",
    english_plural: "pizzas",
    chinese_meaning: "披薩",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 57,
    english_singular: "hot dog",
    english_plural: "hot dogs",
    chinese_meaning: "熱狗",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 58,
    english_singular: "chicken nugget",
    english_plural: "chicken nuggets",
    chinese_meaning: "雞塊",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 59,
    english_singular: "soda",
    english_plural: "sodas",
    chinese_meaning: "汽水",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },

  // Bakery & Snacks (theme_id: 7) - words 60-65
  {
    id: 60,
    english_singular: "bread",
    english_plural: "breads",
    chinese_meaning: "麵包",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 61,
    english_singular: "cake",
    english_plural: "cakes",
    chinese_meaning: "蛋糕",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 62,
    english_singular: "cookie",
    english_plural: "cookies",
    chinese_meaning: "餅乾",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 63,
    english_singular: "donut",
    english_plural: "donuts",
    chinese_meaning: "甜甜圈",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 64,
    english_singular: "pie",
    english_plural: "pies",
    chinese_meaning: "派",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 65,
    english_singular: "candy",
    english_plural: "candies",
    chinese_meaning: "糖果",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },

  // Days of Week (theme_id: 8) - words 66-72
  {
    id: 66,
    english_singular: "Monday",
    english_plural: "Mondays",
    chinese_meaning: "星期一",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 67,
    english_singular: "Tuesday",
    english_plural: "Tuesdays",
    chinese_meaning: "星期二",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 68,
    english_singular: "Wednesday",
    english_plural: "Wednesdays",
    chinese_meaning: "星期三",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 69,
    english_singular: "Thursday",
    english_plural: "Thursdays",
    chinese_meaning: "星期四",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 70,
    english_singular: "Friday",
    english_plural: "Fridays",
    chinese_meaning: "星期五",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 71,
    english_singular: "Saturday",
    english_plural: "Saturdays",
    chinese_meaning: "星期六",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 72,
    english_singular: "Sunday",
    english_plural: "Sundays",
    chinese_meaning: "星期日",
    part_of_speech: "noun",
    has_plural: true,
  },

  // Months (theme_id: 9) - words 73-84
  {
    id: 73,
    english_singular: "January",
    english_plural: "Januarys",
    chinese_meaning: "一月",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 74,
    english_singular: "February",
    english_plural: "Februarys",
    chinese_meaning: "二月",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 75,
    english_singular: "March",
    english_plural: "Marchs",
    chinese_meaning: "三月",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 76,
    english_singular: "April",
    english_plural: "April",
    chinese_meaning: "四月",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 77,
    english_singular: "May",
    english_plural: "May",
    chinese_meaning: "五月",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 78,
    english_singular: "June",
    english_plural: "June",
    chinese_meaning: "六月",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 79,
    english_singular: "July",
    english_plural: "July",
    chinese_meaning: "七月",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 80,
    english_singular: "August",
    english_plural: "August",
    chinese_meaning: "八月",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 81,
    english_singular: "September",
    english_plural: "September",
    chinese_meaning: "九月",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 82,
    english_singular: "October",
    english_plural: "October",
    chinese_meaning: "十月",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 83,
    english_singular: "November",
    english_plural: "November",
    chinese_meaning: "十一月",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 84,
    english_singular: "December",
    english_plural: "December",
    chinese_meaning: "十二月",
    part_of_speech: "noun",
    has_plural: true,
  },

  // School Subjects (theme_id: 10) - words 85-95
  {
    id: 85,
    english_singular: "Math",
    english_plural: "Maths",
    chinese_meaning: "數學",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 86,
    english_singular: "English",
    english_plural: "English",
    chinese_meaning: "英文",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 87,
    english_singular: "Science",
    english_plural: "Sciences",
    chinese_meaning: "科學",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 88,
    english_singular: "History",
    english_plural: "Histories",
    chinese_meaning: "歷史",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 89,
    english_singular: "Geography",
    english_plural: "Geographies",
    chinese_meaning: "地理",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 90,
    english_singular: "Art",
    english_plural: "Arts",
    chinese_meaning: "藝術",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 91,
    english_singular: "Music",
    english_plural: "Musics",
    chinese_meaning: "音樂",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 92,
    english_singular: "Physical Education",
    english_plural: "Physical Educations",
    chinese_meaning: "體育",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 93,
    english_singular: "Social Studies",
    english_plural: "Social Studies",
    chinese_meaning: "社會研究",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 94,
    english_singular: "Chinese",
    english_plural: "Chinese",
    chinese_meaning: "中文",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 95,
    english_singular: "Japanese",
    english_plural: "Japanese",
    chinese_meaning: "日文",
    part_of_speech: "noun",
    has_plural: true,
  },

  // Ailments (theme_id: 11) - words 96-99
  {
    id: 96,
    english_singular: "headache",
    english_plural: "headaches",
    chinese_meaning: "頭痛",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 97,
    english_singular: "cold",
    english_plural: "colds",
    chinese_meaning: "感冒",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 98,
    english_singular: "flu",
    english_plural: "flu",
    chinese_meaning: "流感",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 99,
    english_singular: "allergy",
    english_plural: "allergies",
    chinese_meaning: "過敏",
    part_of_speech: "noun",
    has_plural: true,
  },

  // Countries (theme_id: 12) - words 100-101
  {
    id: 100,
    english_singular: "China",
    english_plural: "China",
    chinese_meaning: "中國",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 101,
    english_singular: "USA",
    english_plural: "USA",
    chinese_meaning: "美國",
    part_of_speech: "noun",
    has_plural: true,
  },

  // Furniture (theme_id: 13) - words 42-47
  {
    id: 42,
    english_singular: "chair",
    english_plural: "chairs",
    chinese_meaning: "椅子",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 43,
    english_singular: "table",
    english_plural: "tables",
    chinese_meaning: "桌子",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 44,
    english_singular: "bed",
    english_plural: "beds",
    chinese_meaning: "床",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 45,
    english_singular: "desk",
    english_plural: "desks",
    chinese_meaning: "書桌",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 46,
    english_singular: "sofa",
    english_plural: "sofas",
    chinese_meaning: "沙發",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 47,
    english_singular: "lamp",
    english_plural: "lamps",
    chinese_meaning: "檯燈",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },

  // Drinks (theme_id: 15) - words 48-53
  {
    id: 48,
    english_singular: "water",
    english_plural: "waters",
    chinese_meaning: "水",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 49,
    english_singular: "milk",
    english_plural: "milks",
    chinese_meaning: "牛奶",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 50,
    english_singular: "juice",
    english_plural: "juices",
    chinese_meaning: "果汁",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 51,
    english_singular: "tea",
    english_plural: "teas",
    chinese_meaning: "茶",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 52,
    english_singular: "coffee",
    english_plural: "coffees",
    chinese_meaning: "咖啡",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },

  // Fast Food (theme_id: 6) - words 54-59
  {
    id: 54,
    english_singular: "hamburger",
    english_plural: "hamburgers",
    chinese_meaning: "漢堡",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 55,
    english_singular: "fries",
    english_plural: "fries",
    chinese_meaning: "薯條",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 56,
    english_singular: "pizza",
    english_plural: "pizzas",
    chinese_meaning: "披薩",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 57,
    english_singular: "hot dog",
    english_plural: "hot dogs",
    chinese_meaning: "熱狗",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 58,
    english_singular: "chicken nugget",
    english_plural: "chicken nuggets",
    chinese_meaning: "雞塊",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 59,
    english_singular: "soda",
    english_plural: "sodas",
    chinese_meaning: "汽水",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },

  // Toys words (Theme 14) - all have plurals
  {
    id: 300,
    english_singular: "doll",
    english_plural: "dolls",
    chinese_meaning: "娃娃",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 301,
    english_singular: "car",
    english_plural: "cars",
    chinese_meaning: "車子",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 302,
    english_singular: "ball",
    english_plural: "balls",
    chinese_meaning: "球",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 303,
    english_singular: "robot",
    english_plural: "robots",
    chinese_meaning: "機器人",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 304,
    english_singular: "puzzle",
    english_plural: "puzzles",
    chinese_meaning: "拼圖",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 305,
    english_singular: "teddy bear",
    english_plural: "teddy bears",
    chinese_meaning: "泰迪熊",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },

  // Main Dishes (theme_id: 16) - words 140-141
  {
    id: 140,
    english_singular: "fried rice",
    english_plural: "fried rices",
    chinese_meaning: "炒飯",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 141,
    english_singular: "dumpling",
    english_plural: "dumplings",
    chinese_meaning: "餃子",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },

  // Bubble Tea Toppings (theme_id: 17) - words 142-143
  {
    id: 142,
    english_singular: "bubble",
    english_plural: "bubbles",
    chinese_meaning: "珍珠",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },
  {
    id: 143,
    english_singular: "jelly",
    english_plural: "jellies",
    chinese_meaning: "果凍",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },

  // Identity (theme_id: 18) - words 102-111
  {
    id: 102,
    english_singular: "student",
    english_plural: "students",
    chinese_meaning: "學生",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 103,
    english_singular: "teacher",
    english_plural: "teachers",
    chinese_meaning: "老師",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 104,
    english_singular: "friend",
    english_plural: "friends",
    chinese_meaning: "朋友",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 105,
    english_singular: "classmate",
    english_plural: "classmates",
    chinese_meaning: "同學",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 106,
    english_singular: "family",
    english_plural: "families",
    chinese_meaning: "家人",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 107,
    english_singular: "parent",
    english_plural: "parents",
    chinese_meaning: "父母",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 108,
    english_singular: "child",
    english_plural: "children",
    chinese_meaning: "小孩",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 109,
    english_singular: "sister",
    english_plural: "sisters",
    chinese_meaning: "姐妹",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 110,
    english_singular: "brother",
    english_plural: "brothers",
    chinese_meaning: "兄弟",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 111,
    english_singular: "cousin",
    english_plural: "cousins",
    chinese_meaning: "堂/表兄弟姊妹",
    part_of_speech: "noun",
    has_plural: true,
    image_url: undefined,
    audio_url: undefined,
  },

  // Professions (theme_id: 19) - words 112-137
  {
    id: 112,
    english_singular: "doctor",
    english_plural: "doctors",
    chinese_meaning: "醫生",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 113,
    english_singular: "nurse",
    english_plural: "nurses",
    chinese_meaning: "護士",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 114,
    english_singular: "engineer",
    english_plural: "engineers",
    chinese_meaning: "工程師",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 115,
    english_singular: "artist",
    english_plural: "artists",
    chinese_meaning: "藝術家",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 116,
    english_singular: "chef",
    english_plural: "chefs",
    chinese_meaning: "廚師",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 117,
    english_singular: "driver",
    english_plural: "drivers",
    chinese_meaning: "司機",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 118,
    english_singular: "police officer",
    english_plural: "police officers",
    chinese_meaning: "警察",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 119,
    english_singular: "firefighter",
    english_plural: "firefighters",
    chinese_meaning: "消防員",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 120,
    english_singular: "scientist",
    english_plural: "scientists",
    chinese_meaning: "科學家",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 121,
    english_singular: "musician",
    english_plural: "musicians",
    chinese_meaning: "音樂家",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 122,
    english_singular: "dentist",
    english_plural: "dentists",
    chinese_meaning: "牙醫",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 123,
    english_singular: "lawyer",
    english_plural: "lawyers",
    chinese_meaning: "律師",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 124,
    english_singular: "architect",
    english_plural: "architects",
    chinese_meaning: "建築師",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 125,
    english_singular: "designer",
    english_plural: "designers",
    chinese_meaning: "設計師",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 126,
    english_singular: "photographer",
    english_plural: "photographers",
    chinese_meaning: "攝影師",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 127,
    english_singular: "journalist",
    english_plural: "journalists",
    chinese_meaning: "記者",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 128,
    english_singular: "accountant",
    english_plural: "accountants",
    chinese_meaning: "會計師",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 129,
    english_singular: "salesperson",
    english_plural: "salespeople",
    chinese_meaning: "銷售員",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 130,
    english_singular: "waiter",
    english_plural: "waiters",
    chinese_meaning: "服務生",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 131,
    english_singular: "waitress",
    english_plural: "waitresses",
    chinese_meaning: "女服務生",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 132,
    english_singular: "pilot",
    english_plural: "pilots",
    chinese_meaning: "飛行員",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 133,
    english_singular: "sailor",
    english_plural: "sailors",
    chinese_meaning: "水手",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 134,
    english_singular: "farmer",
    english_plural: "farmers",
    chinese_meaning: "農夫",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 135,
    english_singular: "fisherman",
    english_plural: "fishermen",
    chinese_meaning: "漁夫",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 136,
    english_singular: "carpenter",
    english_plural: "carpenters",
    chinese_meaning: "木匠",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 137,
    english_singular: "plumber",
    english_plural: "plumbers",
    chinese_meaning: "水管工",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 138,
    english_singular: "electrician",
    english_plural: "electricians",
    chinese_meaning: "電工",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 139,
    english_singular: "mechanic",
    english_plural: "mechanics",
    chinese_meaning: "技工",
    part_of_speech: "noun",
    has_plural: true,
  },

  // Daily Actions (theme_id: 20) - words 144-159
  {
    id: 144,
    english_singular: "wake up",
    english_plural: "wake ups",
    chinese_meaning: "起床",
    part_of_speech: "verb",
    has_plural: true,
  },
  {
    id: 145,
    english_singular: "get up",
    english_plural: "get ups",
    chinese_meaning: "起床",
    part_of_speech: "verb",
    has_plural: true,
  },
  {
    id: 146,
    english_singular: "brush teeth",
    english_plural: "brush teeth",
    chinese_meaning: "刷牙",
    part_of_speech: "verb",
    has_plural: true,
  },
  {
    id: 147,
    english_singular: "wash face",
    english_plural: "wash face",
    chinese_meaning: "洗臉",
    part_of_speech: "verb",
    has_plural: true,
  },
  {
    id: 148,
    english_singular: "take a shower",
    english_plural: "take showers",
    chinese_meaning: "洗澡",
    part_of_speech: "verb",
    has_plural: true,
  },
  {
    id: 149,
    english_singular: "eat breakfast",
    english_plural: "eat breakfasts",
    chinese_meaning: "吃早餐",
    part_of_speech: "verb",
    has_plural: true,
  },
  {
    id: 150,
    english_singular: "go to school",
    english_plural: "go to schools",
    chinese_meaning: "上學",
    part_of_speech: "verb",
    has_plural: true,
  },
  {
    id: 151,
    english_singular: "study",
    english_plural: "studies",
    chinese_meaning: "讀書",
    part_of_speech: "verb",
    has_plural: true,
  },
  {
    id: 152,
    english_singular: "read",
    english_plural: "reads",
    chinese_meaning: "閱讀",
    part_of_speech: "verb",
    has_plural: true,
  },
  {
    id: 153,
    english_singular: "write",
    english_plural: "writes",
    chinese_meaning: "寫字",
    part_of_speech: "verb",
    has_plural: true,
  },
  {
    id: 154,
    english_singular: "listen",
    english_plural: "listens",
    chinese_meaning: "聽",
    part_of_speech: "verb",
    has_plural: true,
  },
  {
    id: 155,
    english_singular: "speak",
    english_plural: "speaks",
    chinese_meaning: "說話",
    part_of_speech: "verb",
    has_plural: true,
  },
  {
    id: 156,
    english_singular: "cook",
    english_plural: "cooks",
    chinese_meaning: "煮飯",
    part_of_speech: "verb",
    has_plural: true,
  },
  {
    id: 157,
    english_singular: "clean",
    english_plural: "cleans",
    chinese_meaning: "打掃",
    part_of_speech: "verb",
    has_plural: true,
  },
  {
    id: 158,
    english_singular: "sleep",
    english_plural: "sleeps",
    chinese_meaning: "睡覺",
    part_of_speech: "verb",
    has_plural: true,
  },
  {
    id: 159,
    english_singular: "work",
    english_plural: "works",
    chinese_meaning: "工作",
    part_of_speech: "verb",
    has_plural: true,
  },

  // Clothing (theme_id: 21) - words 160-175
  {
    id: 160,
    english_singular: "shirt",
    english_plural: "shirts",
    chinese_meaning: "襯衫",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 161,
    english_singular: "pants",
    english_plural: "pants",
    chinese_meaning: "褲子",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 162,
    english_singular: "dress",
    english_plural: "dresses",
    chinese_meaning: "洋裝",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 163,
    english_singular: "skirt",
    english_plural: "skirts",
    chinese_meaning: "裙子",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 164,
    english_singular: "jacket",
    english_plural: "jackets",
    chinese_meaning: "外套",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 165,
    english_singular: "coat",
    english_plural: "coats",
    chinese_meaning: "大衣",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 166,
    english_singular: "sweater",
    english_plural: "sweaters",
    chinese_meaning: "毛衣",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 167,
    english_singular: "hat",
    english_plural: "hats",
    chinese_meaning: "帽子",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 168,
    english_singular: "cap",
    english_plural: "caps",
    chinese_meaning: "棒球帽",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 169,
    english_singular: "shoes",
    english_plural: "shoes",
    chinese_meaning: "鞋子",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 170,
    english_singular: "sneakers",
    english_plural: "sneakers",
    chinese_meaning: "運動鞋",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 171,
    english_singular: "boots",
    english_plural: "boots",
    chinese_meaning: "靴子",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 172,
    english_singular: "socks",
    english_plural: "socks",
    chinese_meaning: "襪子",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 173,
    english_singular: "underwear",
    english_plural: "underwear",
    chinese_meaning: "內衣",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 174,
    english_singular: "belt",
    english_plural: "belts",
    chinese_meaning: "皮帶",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 175,
    english_singular: "scarf",
    english_plural: "scarves",
    chinese_meaning: "圍巾",
    part_of_speech: "noun",
    has_plural: true,
  },

  // Buildings & Places (theme_id: 22) - words 176-195
  {
    id: 176,
    english_singular: "school",
    english_plural: "schools",
    chinese_meaning: "學校",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 177,
    english_singular: "hospital",
    english_plural: "hospitals",
    chinese_meaning: "醫院",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 178,
    english_singular: "library",
    english_plural: "libraries",
    chinese_meaning: "圖書館",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 179,
    english_singular: "bank",
    english_plural: "banks",
    chinese_meaning: "銀行",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 180,
    english_singular: "post office",
    english_plural: "post offices",
    chinese_meaning: "郵局",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 181,
    english_singular: "police station",
    english_plural: "police stations",
    chinese_meaning: "警察局",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 182,
    english_singular: "fire station",
    english_plural: "fire stations",
    chinese_meaning: "消防局",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 183,
    english_singular: "restaurant",
    english_plural: "restaurants",
    chinese_meaning: "餐廳",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 184,
    english_singular: "cafe",
    english_plural: "cafes",
    chinese_meaning: "咖啡廳",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 185,
    english_singular: "supermarket",
    english_plural: "supermarkets",
    chinese_meaning: "超市",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 186,
    english_singular: "store",
    english_plural: "stores",
    chinese_meaning: "商店",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 187,
    english_singular: "shop",
    english_plural: "shops",
    chinese_meaning: "商店",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 188,
    english_singular: "market",
    english_plural: "markets",
    chinese_meaning: "市場",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 189,
    english_singular: "pharmacy",
    english_plural: "pharmacies",
    chinese_meaning: "藥局",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 190,
    english_singular: "gas station",
    english_plural: "gas stations",
    chinese_meaning: "加油站",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 191,
    english_singular: "bus stop",
    english_plural: "bus stops",
    chinese_meaning: "公車站",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 192,
    english_singular: "train station",
    english_plural: "train stations",
    chinese_meaning: "火車站",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 193,
    english_singular: "airport",
    english_plural: "airports",
    chinese_meaning: "機場",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 194,
    english_singular: "park",
    english_plural: "parks",
    chinese_meaning: "公園",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 195,
    english_singular: "museum",
    english_plural: "museums",
    chinese_meaning: "博物館",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 196,
    english_singular: "cinema",
    english_plural: "cinemas",
    chinese_meaning: "電影院",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 197,
    english_singular: "theater",
    english_plural: "theaters",
    chinese_meaning: "劇院",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 198,
    english_singular: "hotel",
    english_plural: "hotels",
    chinese_meaning: "旅館",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 199,
    english_singular: "office",
    english_plural: "offices",
    chinese_meaning: "辦公室",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 200,
    english_singular: "house",
    english_plural: "houses",
    chinese_meaning: "房子",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 201,
    english_singular: "apartment",
    english_plural: "apartments",
    chinese_meaning: "公寓",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 202,
    english_singular: "building",
    english_plural: "buildings",
    chinese_meaning: "建築物",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 203,
    english_singular: "street",
    english_plural: "streets",
    chinese_meaning: "街道",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 204,
    english_singular: "road",
    english_plural: "roads",
    chinese_meaning: "道路",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 205,
    english_singular: "bridge",
    english_plural: "bridges",
    chinese_meaning: "橋樑",
    part_of_speech: "noun",
    has_plural: true,
  },
  {
    id: 206,
    english_singular: "tower",
    english_plural: "towers",
    chinese_meaning: "塔",
    part_of_speech: "noun",
    has_plural: true,
  },
];

// Mock sentence patterns that match the D1 database schema exactly
// IMPORTANT: Only questions are displayed in the UI, answers are linked via question_answer_pairs
const mockSentencePatterns = [
  // Grade 3 patterns (grade_id: 1) - Only Questions and Statements
  {
    id: 1,
    grade_id: 1, // Grade 3
    pattern_text: "How old _____?",
    pattern_type: "Question" as const,
    notes: "Age question pattern",
  },
  {
    id: 3,
    grade_id: 1, // Grade 3
    pattern_text: "Are you a student?",
    pattern_type: "Question" as const,
    notes: "Yes/No question with be verb",
  },
  {
    id: 6,
    grade_id: 1, // Grade 3
    pattern_text: "Is he/she a teacher?",
    pattern_type: "Question" as const,
    notes: "Yes/No question with be verb for third person",
  },
  {
    id: 9,
    grade_id: 1, // Grade 3
    pattern_text: "Are you happy?",
    pattern_type: "Question" as const,
    notes: "Yes/No question with adjective",
  },
  {
    id: 12,
    grade_id: 1, // Grade 3
    pattern_text: "What's this/that?",
    pattern_type: "Question" as const,
    notes: "Identification question",
  },
  {
    id: 14,
    grade_id: 1, // Grade 3
    pattern_text: "What are these/those?",
    pattern_type: "Question" as const,
    notes: "Plural identification question",
  },
  {
    id: 16,
    grade_id: 1, // Grade 3
    pattern_text: "What color is it?",
    pattern_type: "Question" as const,
    notes: "Color question",
  },
  {
    id: 18,
    grade_id: 1, // Grade 3
    pattern_text: "Who is he/she?",
    pattern_type: "Question" as const,
    notes: "Person identification question",
  },
  {
    id: 20,
    grade_id: 1, // Grade 3
    pattern_text: "I have a _____.",
    pattern_type: "Statement" as const,
    notes: "Possession pattern",
  },
  {
    id: 21,
    grade_id: 1, // Grade 3
    pattern_text: "Do you have a pen/an eraser?",
    pattern_type: "Question" as const,
    notes: "Possession question",
  },
  {
    id: 24,
    grade_id: 1, // Grade 3
    pattern_text: "What does he/she like?",
    pattern_type: "Question" as const,
    notes: "Preference question for third person",
  },
  {
    id: 25,
    grade_id: 1, // Grade 3
    pattern_text: "Removed pattern",
    pattern_type: "Question" as const,
    notes: "Removed - no fill-in-blank slot",
  },
  {
    id: 28,
    grade_id: 1, // Grade 3
    pattern_text: "How much is it?",
    pattern_type: "Question" as const,
    notes: "Price question",
  },
  {
    id: 30,
    grade_id: 1, // Grade 3
    pattern_text: "Where's _____?",
    pattern_type: "Question" as const,
    notes: "Location question",
  },

  // Grade 5 patterns (grade_id: 2) - Only Questions
  {
    id: 32,
    grade_id: 2, // Grade 5
    pattern_text: "Do you like sports?",
    pattern_type: "Question" as const,
    notes: "Sports preference question",
  },
  {
    id: 34,
    grade_id: 2, // Grade 5
    pattern_text: "Does he/she like tea?",
    pattern_type: "Question" as const,
    notes: "Third person preference question",
  },
  {
    id: 37,
    grade_id: 2, // Grade 5
    pattern_text: "How many _____ do you need?",
    pattern_type: "Question" as const,
    notes: "Quantity question for second person",
  },
  {
    id: 41,
    grade_id: 2, // Grade 5
    pattern_text: "What day is today?",
    pattern_type: "Question" as const,
    notes: "Day question",
  },
  {
    id: 43,
    grade_id: 2, // Grade 5
    pattern_text: "What's your/his/her favorite subject?",
    pattern_type: "Question" as const,
    notes: "Favorite subject question",
  },

  // Grade 6 patterns (grade_id: 3) - Only Questions
  {
    id: 45,
    grade_id: 3, // Grade 6
    pattern_text: "Where are you from?",
    pattern_type: "Question" as const,
    notes: "Origin question for second person",
  },
  {
    id: 47,
    grade_id: 3, // Grade 6
    pattern_text: "Is he/she from _____?",
    pattern_type: "Question" as const,
    notes: "Origin question for third person",
  },
  {
    id: 51,
    grade_id: 3, // Grade 6
    pattern_text: "What would you like to eat?",
    pattern_type: "Question" as const,
    notes: "Food preference question",
  },
  {
    id: 53,
    grade_id: 3, // Grade 6
    pattern_text: "Would you like some _____?",
    pattern_type: "Question" as const,
    notes: "Food offer question",
  },
  {
    id: 56,
    grade_id: 3, // Grade 6
    pattern_text: "What time do you _____?",
    pattern_type: "Question" as const,
    notes: "Time question for routine",
  },
  {
    id: 58,
    grade_id: 3, // Grade 6
    pattern_text: "Do you have lunch at _____?",
    pattern_type: "Question" as const,
    notes: "Lunch time question",
  },

  {
    id: 63,
    grade_id: 3, // Grade 6
    pattern_text: "Does he/she have a fever?",
    pattern_type: "Question" as const,
    notes: "Health question for third person",
  },
];

// Mock question-answer pairs (simplified for development)
const mockQuestionAnswerPairs = [
  // Grade 3 pairs
  { id: 1, question_pattern_id: 1, answer_pattern_id: 2 }, // How old _____? -> I'm _____ years old.
  { id: 2, question_pattern_id: 3, answer_pattern_id: 4 }, // Are you a student? -> Yes, I am.
  { id: 3, question_pattern_id: 3, answer_pattern_id: 5 }, // Are you a student? -> No, I'm not.
  { id: 4, question_pattern_id: 6, answer_pattern_id: 7 }, // Is he/she a teacher? -> Yes, he/she is.
  { id: 5, question_pattern_id: 6, answer_pattern_id: 8 }, // Is he/she a teacher? -> No, he/she isn't.
  { id: 6, question_pattern_id: 9, answer_pattern_id: 10 }, // Are you happy? -> Yes, I am.
  { id: 7, question_pattern_id: 9, answer_pattern_id: 11 }, // Are you happy? -> No, I'm not.
  { id: 8, question_pattern_id: 12, answer_pattern_id: 13 }, // What's this/that? -> This/It is _____.
  { id: 9, question_pattern_id: 14, answer_pattern_id: 15 }, // What are these/those? -> They are _____.
  { id: 10, question_pattern_id: 16, answer_pattern_id: 17 }, // What color is it? -> It is ____.
  { id: 11, question_pattern_id: 18, answer_pattern_id: 19 }, // Who is he/she? -> He/She is my _____.
  { id: 12, question_pattern_id: 21, answer_pattern_id: 22 }, // Do you have a pen/an eraser? -> Yes, I do.
  { id: 13, question_pattern_id: 21, answer_pattern_id: 23 }, // Do you have a pen/an eraser? -> No, I don't.

  { id: 16, question_pattern_id: 28, answer_pattern_id: 29 }, // How much is it? -> It's _____ dollars.
  { id: 17, question_pattern_id: 30, answer_pattern_id: 17 }, // Where's _____? -> It is ____. (shared answer)

  // Grade 5 pairs
  { id: 18, question_pattern_id: 32, answer_pattern_id: 33 }, // Do you like sports? -> I like _____.
  { id: 19, question_pattern_id: 34, answer_pattern_id: 35 }, // Does he/she like tea? -> Yes, she/he does.
  { id: 20, question_pattern_id: 34, answer_pattern_id: 36 }, // Does he/she like tea? -> No, she/he doesn't
  { id: 21, question_pattern_id: 37, answer_pattern_id: 38 }, // How many _____ do you need? -> I need _____ _____.
  { id: 23, question_pattern_id: 41, answer_pattern_id: 42 }, // What day is today? -> It's _____.
  { id: 24, question_pattern_id: 43, answer_pattern_id: 44 }, // What's your/his/her favorite subject? -> My/she/he favorite subject is _____.

  // Grade 6 pairs
  { id: 25, question_pattern_id: 45, answer_pattern_id: 46 }, // Where are you from? -> I'm from _____.
  { id: 26, question_pattern_id: 47, answer_pattern_id: 48 }, // Is he/she from _____? -> Yes, _____ is.
  { id: 27, question_pattern_id: 47, answer_pattern_id: 49 }, // Is he/she from _____? -> No, _____ isn't.
  { id: 28, question_pattern_id: 51, answer_pattern_id: 52 }, // What would you like to eat? -> I would like some _____, please.
  { id: 29, question_pattern_id: 53, answer_pattern_id: 54 }, // Would you like some _____? -> Yes, please
  { id: 30, question_pattern_id: 53, answer_pattern_id: 55 }, // Would you like some _____? -> No, thank you.
  { id: 31, question_pattern_id: 56, answer_pattern_id: 57 }, // What time do you _____? -> I _____ at _____.
  { id: 32, question_pattern_id: 58, answer_pattern_id: 59 }, // Do you have lunch at _____? -> Yes, I do.
  { id: 33, question_pattern_id: 58, answer_pattern_id: 60 }, // Do you have lunch at _____? -> No, I don't.

  { id: 35, question_pattern_id: 63, answer_pattern_id: 64 }, // Does he/she have a fever? -> Yes, he/she does.
  { id: 36, question_pattern_id: 63, answer_pattern_id: 65 }, // Does he/she have a fever? -> No, he/she doesn't
];

// Word theme associations (simplified for mock)
const wordThemeMap = new Map<number, number[]>([
  // Emotions (theme_id: 1) - words 1-8
  [1, [1]],
  [2, [1]],
  [3, [1]],
  [4, [1]],
  [5, [1]],
  [6, [1]],
  [7, [1]],
  [8, [1]],

  // Colors (theme_id: 2) - words 9-19
  [9, [2]],
  [10, [2]],
  [11, [2]],
  [12, [2]],
  [13, [2]],
  [14, [2]],
  [15, [2]],
  [16, [2]],
  [17, [2]],
  [18, [2]],
  [19, [2]],
  // Additional color words as nouns
  [200, [2]],
  [201, [2]],
  [202, [2]],
  [203, [2]],
  [204, [2]],
  [205, [2]],
  [206, [2]],
  [207, [2]],
  [208, [2]],
  [209, [2]],

  // Sports (theme_id: 3) - words 20-27
  [20, [3]],
  [21, [3]],
  [22, [3]],
  [23, [3]],
  [24, [3]],
  [25, [3]],
  [26, [3]],
  [27, [3]],

  // Stationery (theme_id: 4) - words 28-34
  [28, [4]],
  [29, [4]],
  [30, [4]],
  [31, [4]],
  [32, [4]],
  [33, [4]],
  [34, [4]],

  // Fruits (theme_id: 5) - words 35-41
  [35, [5]],
  [36, [5]],
  [37, [5]],
  [38, [5]],
  [39, [5]],
  [40, [5]],
  [41, [5]],

  // Fast Food (theme_id: 6) - words 54-59
  [54, [6]],
  [55, [6]],
  [56, [6]],
  [57, [6]],
  [58, [6]],
  [59, [6]],

  // Bakery & Snacks (theme_id: 7) - words 60-65
  [60, [7]],
  [61, [7]],
  [62, [7]],
  [63, [7]],
  [64, [7]],
  [65, [7]],

  // Days of Week (theme_id: 8) - words 66-72
  [66, [8]],
  [67, [8]],
  [68, [8]],
  [69, [8]],
  [70, [8]],
  [71, [8]],
  [72, [8]],

  // Months (theme_id: 9) - words 73-84
  [73, [9]],
  [74, [9]],
  [75, [9]],
  [76, [9]],
  [77, [9]],
  [78, [9]],
  [79, [9]],
  [80, [9]],
  [81, [9]],
  [82, [9]],
  [83, [9]],
  [84, [9]],

  // School Subjects (theme_id: 10) - words 85-95
  [85, [10]],
  [86, [10]],
  [87, [10]],
  [88, [10]],
  [89, [10]],
  [90, [10]],
  [91, [10]],
  [92, [10]],
  [93, [10]],
  [94, [10]],
  [95, [10]],

  // Ailments (theme_id: 11) - words 96-99
  [96, [11]],
  [97, [11]],
  [98, [11]],
  [99, [11]],

  // Countries (theme_id: 12) - words 100-101
  [100, [12]],
  [101, [12]],

  // Furniture (theme_id: 13) - words 42-47
  [42, [13]],
  [43, [13]],
  [44, [13]],
  [45, [13]],
  [46, [13]],
  [47, [13]],

  // Toys (theme_id: 14) - words 300-305
  [300, [14]],
  [301, [14]],
  [302, [14]],
  [303, [14]],
  [304, [14]],
  [305, [14]],

  // Drinks (theme_id: 15) - words 48-53
  [48, [15]],
  [49, [15]],
  [50, [15]],
  [51, [15]],
  [52, [15]],
  [53, [15]],

  // Main Dishes (theme_id: 16) - words 140-141
  [140, [16]],
  [141, [16]],

  // Bubble Tea Toppings (theme_id: 17) - words 142-143
  [142, [17]],
  [143, [17]],

  // Identity (theme_id: 18) - words 102-111
  [102, [18]],
  [103, [18]],
  [104, [18]],
  [105, [18]],
  [106, [18]],
  [107, [18]],
  [108, [18]],
  [109, [18]],
  [110, [18]],
  [111, [18]],

  // Professions (theme_id: 19) - words 122-137
  [122, [19]],
  [123, [19]],
  [124, [19]],
  [125, [19]],
  [126, [19]],
  [127, [19]],
  [128, [19]],
  [129, [19]],
  [130, [19]],
  [131, [19]],
  [132, [19]],
  [133, [19]],
  [134, [19]],
  [135, [19]],
  [136, [19]],
  [137, [19]],

  // Daily Actions (theme_id: 20) - words 144-159
  [144, [20]],
  [145, [20]],
  [146, [20]],
  [147, [20]],
  [148, [20]],
  [149, [20]],
  [150, [20]],
  [151, [20]],
  [152, [20]],
  [153, [20]],
  [154, [20]],
  [155, [20]],
  [156, [20]],
  [157, [20]],
  [158, [20]],
  [159, [20]],

  // Clothing (theme_id: 21) - words 160-175
  [160, [21]],
  [161, [21]],
  [162, [21]],
  [163, [21]],
  [164, [21]],
  [165, [21]],
  [166, [21]],
  [167, [21]],
  [168, [21]],
  [169, [21]],
  [170, [21]],
  [171, [21]],
  [172, [21]],
  [173, [21]],
  [174, [21]],
  [175, [21]],

  // Buildings & Places (theme_id: 22) - words 176-195
  [176, [22]],
  [177, [22]],
  [178, [22]],
  [179, [22]],
  [180, [22]],
  [181, [22]],
  [182, [22]],
  [183, [22]],
  [184, [22]],
  [185, [22]],
  [186, [22]],
  [187, [22]],
  [188, [22]],
  [189, [22]],
  [190, [22]],
  [191, [22]],
  [192, [22]],
  [193, [22]],
  [194, [22]],
  [195, [22]],
]);

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const action = searchParams.get("action");
    const themeId = searchParams.get("theme_id");
    const gradeId = searchParams.get("grade_id");
    const partOfSpeech = searchParams.get("part_of_speech");

    switch (action) {
      case "themes":
        return getThemes();

      case "words_by_theme":
        if (!themeId) {
          return NextResponse.json(
            { success: false, error: "theme_id is required" },
            { status: 400 }
          );
        }
        return getWordsByTheme(parseInt(themeId), partOfSpeech);

      case "sentence_patterns":
        return getSentencePatterns(gradeId ? parseInt(gradeId) : undefined);

      case "question_answer_pairs":
        return getQuestionAnswerPairs(gradeId ? parseInt(gradeId) : undefined);

      case "grades":
        return getGrades();

      default:
        return NextResponse.json(
          { success: false, error: "Invalid action" },
          { status: 400 }
        );
    }
  } catch (error) {
    console.error("Learning content API error:", error);
    return NextResponse.json(
      { success: false, error: "Internal server error" },
      { status: 500 }
    );
  }
}

function getThemes(): NextResponse<ThemesResponse> {
  return NextResponse.json({
    success: true,
    data: mockThemes,
  });
}

function getWordsByTheme(
  themeId: number,
  partOfSpeech?: string | null
): NextResponse<WordsByThemeResponse> {
  // In real implementation, this would query the D1 database
  // For now, return mock data based on theme
  let filteredWords = mockWords;

  if (partOfSpeech) {
    filteredWords = filteredWords.filter(
      (word) => word.part_of_speech === partOfSpeech
    );
  }

  // Filter by theme (simplified mock logic)
  const themeWords = filteredWords.filter((word) => {
    const wordThemes = wordThemeMap.get(word.id);
    return wordThemes && wordThemes.includes(themeId);
  });

  return NextResponse.json({
    success: true,
    data: themeWords,
  });
}

function getSentencePatterns(
  gradeId?: number
): NextResponse<SentencePatternsResponse> {
  let patterns = mockSentencePatterns;

  if (gradeId) {
    patterns = patterns.filter((pattern) => pattern.grade_id === gradeId);
  }

  // Only return questions and statements (no answers)
  patterns = patterns.filter(
    (pattern) =>
      pattern.pattern_type === "Question" ||
      pattern.pattern_type === "Statement"
  );

  return NextResponse.json({
    success: true,
    data: patterns,
  });
}

function getQuestionAnswerPairs(
  gradeId?: number
): NextResponse<QuestionAnswerPairsResponse> {
  let pairs = mockQuestionAnswerPairs;

  if (gradeId) {
    // Filter pairs based on questions that belong to the specified grade
    const gradeQuestions = mockSentencePatterns
      .filter(
        (pattern) =>
          pattern.grade_id === gradeId && pattern.pattern_type === "Question"
      )
      .map((pattern) => pattern.id);

    pairs = pairs.filter((pair) =>
      gradeQuestions.includes(pair.question_pattern_id)
    );
  }

  return NextResponse.json({
    success: true,
    data: pairs,
  });
}

function getGrades(): NextResponse<LearningContentResponse<typeof mockGrades>> {
  return NextResponse.json({
    success: true,
    data: mockGrades,
  });
}
