-- ========================================
-- COMPLETE DATABASE SCHEMA FOR PRIMARY ENGLISH SUPPORT
-- ========================================
-- This file combines the original schema.sql with the learning content schema
-- Compatible with Cloudflare D1 (SQLite syntax)
-- Last updated: 2024-08-31

-- ========================================
-- ORIGINAL SCHEMA TABLES
-- ========================================

-- 管理員消息表
CREATE TABLE IF NOT EXISTS admin_messages (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

-- 遊戲方法與教學輔具表
CREATE TABLE IF NOT EXISTS game_methods (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  categories TEXT NOT NULL, -- JSON 格式，包含分類如：單字學習、句型練習、口語訓練、教學輔具
  grade1 BOOLEAN NOT NULL DEFAULT FALSE, -- 1年級
  grade2 BOOLEAN NOT NULL DEFAULT FALSE, -- 2年級
  grade3 BOOLEAN NOT NULL DEFAULT FALSE, -- 3年級
  grade4 BOOLEAN NOT NULL DEFAULT FALSE, -- 4年級
  grade5 BOOLEAN NOT NULL DEFAULT FALSE, -- 5年級
  grade6 BOOLEAN NOT NULL DEFAULT FALSE, -- 6年級
  materials TEXT NOT NULL, -- JSON 格式
  instructions TEXT NOT NULL, -- JSON 格式
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

-- 教材表
CREATE TABLE IF NOT EXISTS textbooks (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  publisher TEXT NOT NULL,
  grade TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

-- 單元表
CREATE TABLE IF NOT EXISTS units (
  id TEXT PRIMARY KEY,
  textbook_id TEXT NOT NULL,
  name TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  FOREIGN KEY (textbook_id) REFERENCES textbooks(id) ON DELETE CASCADE
);

-- 單字表
CREATE TABLE IF NOT EXISTS vocabulary (
  id TEXT PRIMARY KEY,
  unit_id TEXT NOT NULL,
  english TEXT NOT NULL,
  chinese TEXT NOT NULL,
  phonetic TEXT NOT NULL,
  example TEXT NOT NULL,
  image TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  FOREIGN KEY (unit_id) REFERENCES units(id) ON DELETE CASCADE
);

-- ========================================
-- LEARNING CONTENT SCHEMA TABLES
-- ========================================

-- 1. Grades table - Stores grade levels
CREATE TABLE IF NOT EXISTS grades (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE
);

-- 2. Sentence patterns table - Stores sentence patterns for different grades
CREATE TABLE IF NOT EXISTS sentence_patterns (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    grade_id INTEGER NOT NULL,
    pattern_text TEXT NOT NULL,
    pattern_type TEXT NOT NULL CHECK(pattern_type IN ('Question', 'Answer', 'Statement')),
    notes TEXT,
    FOREIGN KEY (grade_id) REFERENCES grades(id) ON DELETE CASCADE
);

-- 3. Question-Answer pairs table - Links questions to their answers
CREATE TABLE IF NOT EXISTS question_answer_pairs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    question_pattern_id INTEGER NOT NULL,
    answer_pattern_id INTEGER NOT NULL,
    FOREIGN KEY (question_pattern_id) REFERENCES sentence_patterns(id) ON DELETE CASCADE,
    FOREIGN KEY (answer_pattern_id) REFERENCES sentence_patterns(id) ON DELETE CASCADE,
    UNIQUE(question_pattern_id, answer_pattern_id)
);

-- 4. Word themes table - Stores categories for words
CREATE TABLE IF NOT EXISTS word_themes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE,
    description TEXT
);

-- 5. Words table - Main dictionary of words with has_plural boolean field
CREATE TABLE IF NOT EXISTS words (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    english_singular TEXT NOT NULL,
    english_plural TEXT,
    chinese_meaning TEXT NOT NULL,
    part_of_speech TEXT NOT NULL CHECK(part_of_speech IN ('noun', 'verb', 'adjective', 'adverb', 'preposition')),
    has_plural BOOLEAN NOT NULL DEFAULT 0,
    image_url TEXT,
    audio_url TEXT
);

-- 6. Pattern slots table - Defines what kind of word each blank needs
CREATE TABLE IF NOT EXISTS pattern_slots (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    pattern_id INTEGER NOT NULL,
    slot_index INTEGER NOT NULL,
    required_part_of_speech TEXT NOT NULL,
    FOREIGN KEY (pattern_id) REFERENCES sentence_patterns(id) ON DELETE CASCADE
);

-- 7. Word theme associations table - Many-to-many relationship between words and themes
CREATE TABLE IF NOT EXISTS word_theme_associations (
    word_id INTEGER NOT NULL,
    theme_id INTEGER NOT NULL,
    PRIMARY KEY (word_id, theme_id),
    FOREIGN KEY (word_id) REFERENCES words(id) ON DELETE CASCADE,
    FOREIGN KEY (theme_id) REFERENCES word_themes(id) ON DELETE CASCADE
);

-- ========================================
-- SAMPLE DATA INSERTION
-- ========================================

-- Insert only the required grade levels
INSERT OR IGNORE INTO grades (name) VALUES 
('Grade 3'),  -- grade_id: 1
('Grade 5'),  -- grade_id: 2
('Grade 6');  -- grade_id: 3

-- Insert word themes
INSERT OR IGNORE INTO word_themes (id, name, description) VALUES
(1, 'Emotions', 'Words related to feelings and emotions'),
(2, 'Colors', 'Words for different colors'),
(3, 'Sports', 'Words related to sports and physical activities'),
(4, 'Stationery', 'Words for school and office supplies'),
(5, 'Fruits', 'Words for different types of fruits'),
(6, 'Fast Food', 'Words for fast food items'),
(7, 'Bakery & Snacks', 'Words for bakery items and snacks'),
(8, 'Days of Week', 'Words for days of the week'),
(9, 'Months', 'Words for months of the year'),
(10, 'School Subjects', 'Words for different school subjects'),
(11, 'Ailments', 'Words for common health problems'),
(12, 'Countries', 'Words for different countries'),
(13, 'Furniture', 'Words for furniture items'),
(14, 'Toys', 'Words for different types of toys'),
(15, 'Drinks', 'Words for different types of drinks'),
(16, 'Main Dishes', 'Words for main course dishes'),
(17, 'Bubble Tea Toppings', 'Words for bubble tea toppings'),
(18, 'Identity', 'Words for personal identity and relationships'),
(19, 'Professions', 'Words for different occupations and jobs'),
(20, 'Daily Actions', 'Words for everyday activities and routines'),
(21, 'Clothing', 'Words for different types of clothing and accessories'),
(22, 'Buildings & Places', 'Words for buildings, stores, and places in the city'),
(23, 'Numbers', 'Words for numbers and counting'),
(24, 'Time Expressions', 'Words for time expressions and clock times');

-- Insert words with their details and has_plural field
INSERT OR IGNORE INTO words (english_singular, english_plural, chinese_meaning, part_of_speech, has_plural, image_url, audio_url) VALUES
-- Emotions (adjective) - no plurals
('happy', NULL, '開心的', 'adjective', 0, NULL, NULL),
('sad', NULL, '傷心的', 'adjective', 0, NULL, NULL),
('angry', NULL, '生氣的', 'adjective', 0, NULL, NULL),
('tired', NULL, '疲倦的', 'adjective', 0, NULL, NULL),
('excited', NULL, '興奮的', 'adjective', 0, NULL, NULL),
('bored', NULL, '無聊的', 'adjective', 0, NULL, NULL),
('surprised', NULL, '驚訝的', 'adjective', 0, NULL, NULL),
('scared', NULL, '害怕的', 'adjective', 0, NULL, NULL),

-- Colors (adjective) - no plurals
('red', NULL, '紅色', 'adjective', 0, NULL, NULL),
('blue', NULL, '藍色', 'adjective', 0, NULL, NULL),
('yellow', NULL, '黃色', 'adjective', 0, NULL, NULL),
('green', NULL, '綠色', 'adjective', 0, NULL, NULL),
('black', NULL, '黑色', 'adjective', 0, NULL, NULL),
('white', NULL, '白色', 'adjective', 0, NULL, NULL),
('pink', NULL, '粉紅色', 'adjective', 0, NULL, NULL),
('purple', NULL, '紫色', 'adjective', 0, NULL, NULL),
('orange', NULL, '橘色', 'adjective', 0, NULL, NULL),
('brown', NULL, '棕色', 'adjective', 0, NULL, NULL),
('gray', NULL, '灰色', 'adjective', 0, NULL, NULL),

-- Sports (noun) - some have plurals
('basketball', 'basketballs', '籃球', 'noun', 1, NULL, NULL),
('soccer', NULL, '足球', 'noun', 0, NULL, NULL),
('baseball', 'baseballs', '棒球', 'noun', 1, NULL, NULL),
('tennis', NULL, '網球', 'noun', 0, NULL, NULL),
('badminton', NULL, '羽毛球', 'noun', 0, NULL, NULL),
('swimming', NULL, '游泳', 'noun', 0, NULL, NULL),
('running', NULL, '跑步', 'noun', 0, NULL, NULL),
('jogging', NULL, '慢跑', 'noun', 0, NULL, NULL),
('volleyball', 'volleyballs', '排球', 'noun', 1, NULL, NULL),
('table tennis', NULL, '桌球', 'noun', 0, NULL, NULL),
('golf', NULL, '高爾夫', 'noun', 0, NULL, NULL),
('hockey', NULL, '曲棍球', 'noun', 0, NULL, NULL),
('rugby', NULL, '橄欖球', 'noun', 0, NULL, NULL),
('cricket', NULL, '板球', 'noun', 0, NULL, NULL),
('boxing', NULL, '拳擊', 'noun', 0, NULL, NULL),
('wrestling', NULL, '摔角', 'noun', 0, NULL, NULL),
('karate', NULL, '空手道', 'noun', 0, NULL, NULL),
('judo', NULL, '柔道', 'noun', 0, NULL, NULL),
('taekwondo', NULL, '跆拳道', 'noun', 0, NULL, NULL),
('cycling', NULL, '騎腳踏車', 'noun', 0, NULL, NULL),
('skating', NULL, '溜冰', 'noun', 0, NULL, NULL),
('skiing', NULL, '滑雪', 'noun', 0, NULL, NULL),
('surfing', NULL, '衝浪', 'noun', 0, NULL, NULL),
('diving', NULL, '潛水', 'noun', 0, NULL, NULL),
('climbing', NULL, '攀岩', 'noun', 0, NULL, NULL),
('hiking', NULL, '健行', 'noun', 0, NULL, NULL),
('fishing', NULL, '釣魚', 'noun', 0, NULL, NULL),
('bowling', NULL, '保齡球', 'noun', 0, NULL, NULL),
('ping pong', NULL, '乒乓球', 'noun', 0, NULL, NULL),

-- Stationery (noun) - all have plurals
('pen', 'pens', '筆', 'noun', 1, NULL, NULL),
('pencil', 'pencils', '鉛筆', 'noun', 1, NULL, NULL),
('eraser', 'erasers', '橡皮擦', 'noun', 1, NULL, NULL),
('ruler', 'rulers', '尺', 'noun', 1, NULL, NULL),
('book', 'books', '書', 'noun', 1, NULL, NULL),
('notebook', 'notebooks', '筆記本', 'noun', 1, NULL, NULL),
('marker', 'markers', '麥克筆', 'noun', 1, NULL, NULL),
('highlighter', 'highlighters', '螢光筆', 'noun', 1, NULL, NULL),
('crayon', 'crayons', '蠟筆', 'noun', 1, NULL, NULL),
('colored pencil', 'colored pencils', '彩色鉛筆', 'noun', 1, NULL, NULL),
('paintbrush', 'paintbrushes', '畫筆', 'noun', 1, NULL, NULL),
('scissors', 'scissors', '剪刀', 'noun', 0, NULL, NULL),
('stapler', 'staplers', '訂書機', 'noun', 1, NULL, NULL),
('staples', 'staples', '訂書針', 'noun', 1, NULL, NULL),
('paper clip', 'paper clips', '迴紋針', 'noun', 1, NULL, NULL),
('binder', 'binders', '活頁夾', 'noun', 1, NULL, NULL),
('folder', 'folders', '資料夾', 'noun', 1, NULL, NULL),
('envelope', 'envelopes', '信封', 'noun', 1, NULL, NULL),
('stamp', 'stamps', '郵票', 'noun', 1, NULL, NULL),
('glue', 'glues', '膠水', 'noun', 1, NULL, NULL),
('tape', 'tapes', '膠帶', 'noun', 1, NULL, NULL),
('whiteboard', 'whiteboards', '白板', 'noun', 1, NULL, NULL),
('chalk', 'chalks', '粉筆', 'noun', 1, NULL, NULL),
('blackboard', 'blackboards', '黑板', 'noun', 1, NULL, NULL),
('projector', 'projectors', '投影機', 'noun', 1, NULL, NULL),
('screen', 'screens', '螢幕', 'noun', 1, NULL, NULL),
('pointer', 'pointers', '指示棒', 'noun', 1, NULL, NULL),
('calendar', 'calendars', '日曆', 'noun', 1, NULL, NULL),
('clock', 'clocks', '時鐘', 'noun', 1, NULL, NULL),
('calculator', 'calculators', '計算機', 'noun', 1, NULL, NULL),
('compass', 'compasses', '圓規', 'noun', 1, NULL, NULL),
('protractor', 'protractors', '量角器', 'noun', 1, NULL, NULL),
('dictionary', 'dictionaries', '字典', 'noun', 1, NULL, NULL),
('atlas', 'atlases', '地圖集', 'noun', 1, NULL, NULL),
('backpack', 'backpacks', '背包', 'noun', 1, NULL, NULL),
('pencil case', 'pencil cases', '鉛筆盒', 'noun', 1, NULL, NULL),
('lunch box', 'lunch boxes', '便當盒', 'noun', 1, NULL, NULL),

-- Fruits (noun) - all have plurals
('apple', 'apples', '蘋果', 'noun', 1, NULL, NULL),
('banana', 'bananas', '香蕉', 'noun', 1, NULL, NULL),
('orange', 'oranges', '橘子', 'noun', 1, NULL, NULL),
('grape', 'grapes', '葡萄', 'noun', 1, NULL, NULL),
('guava', 'guavas', '芭樂', 'noun', 1, NULL, NULL),
('lemon', 'lemons', '檸檬', 'noun', 1, NULL, NULL),
('strawberry', 'strawberries', '草莓', 'noun', 1, NULL, NULL),
('pear', 'pears', '梨子', 'noun', 1, NULL, NULL),
('peach', 'peaches', '桃子', 'noun', 1, NULL, NULL),
('plum', 'plums', '李子', 'noun', 1, NULL, NULL),
('cherry', 'cherries', '櫻桃', 'noun', 1, NULL, NULL),
('apricot', 'apricots', '杏子', 'noun', 1, NULL, NULL),
('mango', 'mangoes', '芒果', 'noun', 1, NULL, NULL),
('pineapple', 'pineapples', '鳳梨', 'noun', 1, NULL, NULL),
('watermelon', 'watermelons', '西瓜', 'noun', 1, NULL, NULL),
('cantaloupe', 'cantaloupes', '哈密瓜', 'noun', 1, NULL, NULL),
('honeydew', 'honeydews', '蜜瓜', 'noun', 1, NULL, NULL),
('kiwi', 'kiwis', '奇異果', 'noun', 1, NULL, NULL),
('papaya', 'papayas', '木瓜', 'noun', 1, NULL, NULL),
('dragon fruit', 'dragon fruits', '火龍果', 'noun', 1, NULL, NULL),
('lychee', 'lychees', '荔枝', 'noun', 1, NULL, NULL),
('longan', 'longans', '龍眼', 'noun', 1, NULL, NULL),
('rambutan', 'rambutans', '紅毛丹', 'noun', 1, NULL, NULL),
('durian', 'durians', '榴槤', 'noun', 1, NULL, NULL),
('jackfruit', 'jackfruits', '波羅蜜', 'noun', 1, NULL, NULL),
('breadfruit', 'breadfruits', '麵包果', 'noun', 1, NULL, NULL),
('fig', 'figs', '無花果', 'noun', 1, NULL, NULL),
('date', 'dates', '椰棗', 'noun', 1, NULL, NULL),
('prune', 'prunes', '梅乾', 'noun', 1, NULL, NULL),
('raisin', 'raisins', '葡萄乾', 'noun', 1, NULL, NULL),
('cranberry', 'cranberries', '蔓越莓', 'noun', 1, NULL, NULL),
('blueberry', 'blueberries', '藍莓', 'noun', 1, NULL, NULL),
('raspberry', 'raspberries', '覆盆子', 'noun', 1, NULL, NULL),
('blackberry', 'blackberries', '黑莓', 'noun', 1, NULL, NULL),
('gooseberry', 'gooseberries', '醋栗', 'noun', 1, NULL, NULL),
('currant', 'currants', '醋栗', 'noun', 1, NULL, NULL),
('mulberry', 'mulberries', '桑葚', 'noun', 1, NULL, NULL),
('persimmon', 'persimmons', '柿子', 'noun', 1, NULL, NULL),
('pomegranate', 'pomegranates', '石榴', 'noun', 1, NULL, NULL),
('star fruit', 'star fruits', '楊桃', 'noun', 1, NULL, NULL),
('custard apple', 'custard apples', '釋迦', 'noun', 1, NULL, NULL),
('soursop', 'soursops', '刺果番荔枝', 'noun', 1, NULL, NULL),
('sapodilla', 'sapodillas', '人心果', 'noun', 1, NULL, NULL),
('sugar apple', 'sugar apples', '糖蘋果', 'noun', 1, NULL, NULL),

-- Fast Food (noun) - some have plurals
('hamburger', 'hamburgers', '漢堡', 'noun', 1, NULL, NULL),
('fries', NULL, '薯條', 'noun', 0, NULL, NULL),
('pizza', 'pizzas', '披薩', 'noun', 1, NULL, NULL),
('hot dog', 'hot dogs', '熱狗', 'noun', 1, NULL, NULL),
('chicken nugget', 'chicken nuggets', '雞塊', 'noun', 1, NULL, NULL),
('soda', 'sodas', '汽水', 'noun', 1, NULL, NULL),

-- Bakery & Snacks (noun) - some have plurals
('bread', NULL, '麵包', 'noun', 0, NULL, NULL),
('cake', 'cakes', '蛋糕', 'noun', 1, NULL, NULL),
('cookie', 'cookies', '餅乾', 'noun', 1, NULL, NULL),
('donut', 'donuts', '甜甜圈', 'noun', 1, NULL, NULL),
('pie', 'pies', '派', 'noun', 1, NULL, NULL),
('candy', 'candies', '糖果', 'noun', 1, NULL, NULL),

-- Days of the Week (noun) - no plurals
('Monday', NULL, '星期一', 'noun', 0, NULL, NULL),
('Tuesday', NULL, '星期二', 'noun', 0, NULL, NULL),
('Wednesday', NULL, '星期三', 'noun', 0, NULL, NULL),
('Thursday', NULL, '星期四', 'noun', 0, NULL, NULL),
('Friday', NULL, '星期五', 'noun', 0, NULL, NULL),
('Saturday', NULL, '星期六', 'noun', 0, NULL, NULL),
('Sunday', NULL, '星期日', 'noun', 0, NULL, NULL),

-- Months (noun) - no plurals
('January', NULL, '一月', 'noun', 0, NULL, NULL),
('February', NULL, '二月', 'noun', 0, NULL, NULL),
('March', NULL, '三月', 'noun', 0, NULL, NULL),
('April', NULL, '四月', 'noun', 0, NULL, NULL),
('May', NULL, '五月', 'noun', 0, NULL, NULL),
('June', NULL, '六月', 'noun', 0, NULL, NULL),
('July', NULL, '七月', 'noun', 0, NULL, NULL),
('August', NULL, '八月', 'noun', 0, NULL, NULL),
('September', NULL, '九月', 'noun', 0, NULL, NULL),
('October', NULL, '十月', 'noun', 0, NULL, NULL),
('November', NULL, '十一月', 'noun', 0, NULL, NULL),
('December', NULL, '十二月', 'noun', 0, NULL, NULL),

-- School Subjects (noun) - some have plurals
('math', NULL, '數學', 'noun', 0, NULL, NULL),
('science', NULL, '科學', 'noun', 0, NULL, NULL),
('English', NULL, '英文', 'noun', 0, NULL, NULL),
('history', NULL, '歷史', 'noun', 0, NULL, NULL),
('geography', NULL, '地理', 'noun', 0, NULL, NULL),
('art', NULL, '美術', 'noun', 0, NULL, NULL),
('music', NULL, '音樂', 'noun', 0, NULL, NULL),
('PE', NULL, '體育', 'noun', 0, NULL, NULL),
('Chinese', NULL, '國文', 'noun', 0, NULL, NULL),
('social studies', NULL, '社會', 'noun', 0, NULL, NULL),
('computer science', NULL, '電腦', 'noun', 0, NULL, NULL),
('physical education', NULL, '體育課', 'noun', 0, NULL, NULL),
('home economics', NULL, '家政', 'noun', 0, NULL, NULL),
('library science', NULL, '圖書館學', 'noun', 0, NULL, NULL),
('cooking', NULL, '烹飪', 'noun', 0, NULL, NULL),
('drama', NULL, '戲劇', 'noun', 0, NULL, NULL),
('dance', NULL, '舞蹈', 'noun', 0, NULL, NULL),
('band', 'bands', '樂隊', 'noun', 1, NULL, NULL),
('choir', 'choirs', '合唱團', 'noun', 1, NULL, NULL),
('debate', 'debates', '辯論', 'noun', 1, NULL, NULL),
('journalism', NULL, '新聞學', 'noun', 0, NULL, NULL),
('yearbook', 'yearbooks', '年鑑', 'noun', 1, NULL, NULL),
('newspaper', 'newspapers', '報紙', 'noun', 1, NULL, NULL),
('magazine', 'magazines', '雜誌', 'noun', 1, NULL, NULL),
('club', 'clubs', '社團', 'noun', 1, NULL, NULL),
('team', 'teams', '隊伍', 'noun', 1, NULL, NULL),
('study group', 'study groups', '讀書會', 'noun', 1, NULL, NULL),
('tutoring', NULL, '補習', 'noun', 0, NULL, NULL),
('homework', NULL, '家庭作業', 'noun', 0, NULL, NULL),
('assignment', 'assignments', '作業', 'noun', 1, NULL, NULL),
('project', 'projects', '專題', 'noun', 1, NULL, NULL),
('presentation', 'presentations', '報告', 'noun', 1, NULL, NULL),
('exam', 'exams', '考試', 'noun', 1, NULL, NULL),
('test', 'tests', '測驗', 'noun', 1, NULL, NULL),
('quiz', 'quizzes', '小考', 'noun', 1, NULL, NULL),
('final exam', 'final exams', '期末考', 'noun', 1, NULL, NULL),
('midterm exam', 'midterm exams', '期中考', 'noun', 1, NULL, NULL),
('pop quiz', 'pop quizzes', '突擊測驗', 'noun', 1, NULL, NULL),
('essay', 'essays', '作文', 'noun', 1, NULL, NULL),
('research paper', 'research papers', '研究報告', 'noun', 1, NULL, NULL),
('book report', 'book reports', '讀書報告', 'noun', 1, NULL, NULL),
('oral report', 'oral reports', '口頭報告', 'noun', 1, NULL, NULL),
('group project', 'group projects', '小組專題', 'noun', 1, NULL, NULL),
('individual project', 'individual projects', '個人專題', 'noun', 1, NULL, NULL),
('science fair', 'science fairs', '科學展覽', 'noun', 1, NULL, NULL),
('art show', 'art shows', '藝術展覽', 'noun', 1, NULL, NULL),
('talent show', 'talent shows', '才藝表演', 'noun', 1, NULL, NULL),
('spelling bee', 'spelling bees', '拼字比賽', 'noun', 1, NULL, NULL),
('math competition', 'math competitions', '數學競賽', 'noun', 1, NULL, NULL),
('science competition', 'science competitions', '科學競賽', 'noun', 1, NULL, NULL),
('reading contest', 'reading contests', '閱讀比賽', 'noun', 1, NULL, NULL),
('writing contest', 'writing contests', '寫作比賽', 'noun', 1, NULL, NULL),
('speech contest', 'speech contests', '演講比賽', 'noun', 1, NULL, NULL),
('debate tournament', 'debate tournaments', '辯論比賽', 'noun', 1, NULL, NULL),
('chess tournament', 'chess tournaments', '象棋比賽', 'noun', 1, NULL, NULL),
('checkers tournament', 'checkers tournaments', '跳棋比賽', 'noun', 1, NULL, NULL),
('board game tournament', 'board game tournaments', '桌遊比賽', 'noun', 1, NULL, NULL),
('card game tournament', 'card game tournaments', '紙牌比賽', 'noun', 1, NULL, NULL),
('video game tournament', 'video game tournaments', '電競比賽', 'noun', 1, NULL, NULL),
('sports tournament', 'sports tournaments', '運動比賽', 'noun', 1, NULL, NULL),
('swimming meet', 'swimming meets', '游泳比賽', 'noun', 1, NULL, NULL),
('track meet', 'track meets', '田徑比賽', 'noun', 1, NULL, NULL),
('basketball game', 'basketball games', '籃球比賽', 'noun', 1, NULL, NULL),
('soccer game', 'soccer games', '足球比賽', 'noun', 1, NULL, NULL),
('baseball game', 'baseball games', '棒球比賽', 'noun', 1, NULL, NULL),
('volleyball game', 'volleyball games', '排球比賽', 'noun', 1, NULL, NULL),
('tennis match', 'tennis matches', '網球比賽', 'noun', 1, NULL, NULL),
('badminton match', 'badminton matches', '羽毛球比賽', 'noun', 1, NULL, NULL),
('table tennis match', 'table tennis matches', '桌球比賽', 'noun', 1, NULL, NULL),
('ping pong match', 'ping pong matches', '乒乓球比賽', 'noun', 1, NULL, NULL),
('golf tournament', 'golf tournaments', '高爾夫比賽', 'noun', 1, NULL, NULL),
('hockey game', 'hockey games', '曲棍球比賽', 'noun', 1, NULL, NULL),
('rugby match', 'rugby matches', '橄欖球比賽', 'noun', 1, NULL, NULL),
('cricket match', 'cricket matches', '板球比賽', 'noun', 1, NULL, NULL),
('boxing match', 'boxing matches', '拳擊比賽', 'noun', 1, NULL, NULL),
('wrestling match', 'wrestling matches', '摔角比賽', 'noun', 1, NULL, NULL),
('karate tournament', 'karate tournaments', '空手道比賽', 'noun', 1, NULL, NULL),
('judo tournament', 'judo tournaments', '柔道比賽', 'noun', 1, NULL, NULL),
('taekwondo tournament', 'taekwondo tournaments', '跆拳道比賽', 'noun', 1, NULL, NULL),
('cycling race', 'cycling races', '腳踏車比賽', 'noun', 1, NULL, NULL),
('skating competition', 'skating competitions', '溜冰比賽', 'noun', 1, NULL, NULL),
('skiing competition', 'skiing competitions', '滑雪比賽', 'noun', 1, NULL, NULL),
('surfing competition', 'surfing competitions', '衝浪比賽', 'noun', 1, NULL, NULL),
('diving competition', 'diving competitions', '潛水比賽', 'noun', 1, NULL, NULL),
('climbing competition', 'climbing competitions', '攀岩比賽', 'noun', 1, NULL, NULL),
('hiking trip', 'hiking trips', '健行活動', 'noun', 1, NULL, NULL),
('fishing trip', 'fishing trips', '釣魚活動', 'noun', 1, NULL, NULL),
('bowling game', 'bowling games', '保齡球遊戲', 'noun', 1, NULL, NULL),
('ping pong game', 'ping pong games', '乒乓球遊戲', 'noun', 1, NULL, NULL),

-- Ailments (noun) - some have plurals
('headache', 'headaches', '頭痛', 'noun', 1, NULL, NULL),
('fever', NULL, '發燒', 'noun', 0, NULL, NULL),
('cold', NULL, '感冒', 'noun', 0, NULL, NULL),
('cough', 'coughs', '咳嗽', 'noun', 1, NULL, NULL),
('sore throat', 'sore throats', '喉嚨痛', 'noun', 1, NULL, NULL),
('stomachache', 'stomachaches', '肚子痛', 'noun', 1, NULL, NULL),
('toothache', 'toothaches', '牙痛', 'noun', 1, NULL, NULL),
('earache', 'earaches', '耳朵痛', 'noun', 1, NULL, NULL),
('backache', 'backaches', '背痛', 'noun', 1, NULL, NULL),
('runny nose', NULL, '流鼻水', 'noun', 0, NULL, NULL),
('sneezing', NULL, '打噴嚏', 'noun', 0, NULL, NULL),
('dizziness', NULL, '頭暈', 'noun', 0, NULL, NULL),
('insomnia', NULL, '失眠', 'noun', 0, NULL, NULL),
('allergy', 'allergies', '過敏', 'noun', 1, NULL, NULL),
('rash', 'rashes', '疹子', 'noun', 1, NULL, NULL),
('bruise', 'bruises', '瘀青', 'noun', 1, NULL, NULL),
('cut', 'cuts', '割傷', 'noun', 1, NULL, NULL),
('burn', 'burns', '燙傷', 'noun', 1, NULL, NULL),
('sprain', 'sprains', '扭傷', 'noun', 1, NULL, NULL),
('broken bone', 'broken bones', '骨折', 'noun', 1, NULL, NULL),
('infection', 'infections', '感染', 'noun', 1, NULL, NULL),
('swelling', NULL, '腫脹', 'noun', 0, NULL, NULL),
('itch', 'itches', '癢', 'noun', 1, NULL, NULL),
('blister', 'blisters', '水泡', 'noun', 1, NULL, NULL),
('scar', 'scars', '疤痕', 'noun', 1, NULL, NULL),
('wound', 'wounds', '傷口', 'noun', 1, NULL, NULL),
('nausea', NULL, '噁心', 'noun', 0, NULL, NULL),
('vomiting', NULL, '嘔吐', 'noun', 0, NULL, NULL),
('diarrhea', NULL, '腹瀉', 'noun', 0, NULL, NULL),
('constipation', NULL, '便秘', 'noun', 0, NULL, NULL),
('indigestion', NULL, '消化不良', 'noun', 0, NULL, NULL),
('heartburn', NULL, '胃灼熱', 'noun', 0, NULL, NULL),
('acid reflux', NULL, '胃酸逆流', 'noun', 0, NULL, NULL),
('ulcer', 'ulcers', '潰瘍', 'noun', 1, NULL, NULL),
('appendicitis', NULL, '闌尾炎', 'noun', 0, NULL, NULL),
('gallstones', NULL, '膽結石', 'noun', 0, NULL, NULL),
('kidney stones', NULL, '腎結石', 'noun', 0, NULL, NULL),
('arthritis', NULL, '關節炎', 'noun', 0, NULL, NULL),
('diabetes', NULL, '糖尿病', 'noun', 0, NULL, NULL),
('hypertension', NULL, '高血壓', 'noun', 0, NULL, NULL),
('asthma', NULL, '氣喘', 'noun', 0, NULL, NULL),
('pneumonia', NULL, '肺炎', 'noun', 0, NULL, NULL),
('bronchitis', NULL, '支氣管炎', 'noun', 0, NULL, NULL),
('sinusitis', NULL, '鼻竇炎', 'noun', 0, NULL, NULL),
('tonsillitis', NULL, '扁桃腺炎', 'noun', 0, NULL, NULL),
('otitis media', NULL, '中耳炎', 'noun', 0, NULL, NULL),
('conjunctivitis', NULL, '結膜炎', 'noun', 0, NULL, NULL),
('dermatitis', NULL, '皮膚炎', 'noun', 0, NULL, NULL),
('eczema', NULL, '濕疹', 'noun', 0, NULL, NULL),
('psoriasis', NULL, '乾癬', 'noun', 0, NULL, NULL),
('acne', NULL, '青春痘', 'noun', 0, NULL, NULL),
('warts', NULL, '疣', 'noun', 0, NULL, NULL),
('moles', NULL, '痣', 'noun', 0, NULL, NULL),
('freckles', NULL, '雀斑', 'noun', 0, NULL, NULL),
('birthmarks', NULL, '胎記', 'noun', 0, NULL, NULL),
('stretch marks', NULL, '妊娠紋', 'noun', 0, NULL, NULL),
('cellulite', NULL, '橘皮組織', 'noun', 0, NULL, NULL),
('varicose veins', NULL, '靜脈曲張', 'noun', 0, NULL, NULL),
('hemorrhoids', NULL, '痔瘡', 'noun', 0, NULL, NULL),
('hernia', 'hernias', '疝氣', 'noun', 1, NULL, NULL),
('cataracts', NULL, '白內障', 'noun', 0, NULL, NULL),
('glaucoma', NULL, '青光眼', 'noun', 0, NULL, NULL),
('macular degeneration', NULL, '黃斑部病變', 'noun', 0, NULL, NULL),
('retinal detachment', NULL, '視網膜剝離', 'noun', 0, NULL, NULL),
('corneal abrasion', 'corneal abrasions', '角膜擦傷', 'noun', 1, NULL, NULL),
('foreign body', 'foreign bodies', '異物', 'noun', 1, NULL, NULL),
('chemical burn', 'chemical burns', '化學灼傷', 'noun', 1, NULL, NULL),
('electrical burn', 'electrical burns', '電灼傷', 'noun', 1, NULL, NULL),
('frostbite', NULL, '凍傷', 'noun', 0, NULL, NULL),
('heat stroke', NULL, '中暑', 'noun', 0, NULL, NULL),
('heat exhaustion', NULL, '熱衰竭', 'noun', 0, NULL, NULL),
('hypothermia', NULL, '體溫過低', 'noun', 0, NULL, NULL),
('dehydration', NULL, '脫水', 'noun', 0, NULL, NULL),
('malnutrition', NULL, '營養不良', 'noun', 0, NULL, NULL),
('obesity', NULL, '肥胖', 'noun', 0, NULL, NULL),
('anorexia', NULL, '厭食症', 'noun', 0, NULL, NULL),
('bulimia', NULL, '暴食症', 'noun', 0, NULL, NULL),
('binge eating disorder', NULL, '暴食症', 'noun', 0, NULL, NULL),
('orthorexia', NULL, '健康飲食症', 'noun', 0, NULL, NULL),
('pica', NULL, '異食症', 'noun', 0, NULL, NULL),
('rumination disorder', NULL, '反芻症', 'noun', 0, NULL, NULL),
('avoidant restrictive food intake disorder', NULL, '迴避性限制性食物攝取症', 'noun', 0, NULL, NULL),
('other specified feeding or eating disorder', NULL, '其他特定的餵食或飲食症', 'noun', 0, NULL, NULL),
('unspecified feeding or eating disorder', NULL, '未特定的餵食或飲食症', 'noun', 0, NULL, NULL),

-- Countries (noun) - no plurals
('Taiwan', NULL, '台灣', 'noun', 0, NULL, NULL),
('Japan', NULL, '日本', 'noun', 0, NULL, NULL),
('Korea', NULL, '韓國', 'noun', 0, NULL, NULL),
('China', NULL, '中國', 'noun', 0, NULL, NULL),
('America', NULL, '美國', 'noun', 0, NULL, NULL),
('Canada', NULL, '加拿大', 'noun', 0, NULL, NULL),
('Australia', NULL, '澳洲', 'noun', 0, NULL, NULL),
('England', NULL, '英國', 'noun', 0, NULL, NULL),
('France', NULL, '法國', 'noun', 0, NULL, NULL),
('Germany', NULL, '德國', 'noun', 0, NULL, NULL),
('Italy', NULL, '義大利', 'noun', 0, NULL, NULL),
('Spain', NULL, '西班牙', 'noun', 0, NULL, NULL),
('Brazil', NULL, '巴西', 'noun', 0, NULL, NULL),
('Mexico', NULL, '墨西哥', 'noun', 0, NULL, NULL),
('India', NULL, '印度', 'noun', 0, NULL, NULL),
('Russia', NULL, '俄羅斯', 'noun', 0, NULL, NULL),
('South Africa', NULL, '南非', 'noun', 0, NULL, NULL),
('Egypt', NULL, '埃及', 'noun', 0, NULL, NULL),
('Thailand', NULL, '泰國', 'noun', 0, NULL, NULL),
('Vietnam', NULL, '越南', 'noun', 0, NULL, NULL),
('Singapore', NULL, '新加坡', 'noun', 0, NULL, NULL),
('Malaysia', NULL, '馬來西亞', 'noun', 0, NULL, NULL),
('Philippines', NULL, '菲律賓', 'noun', 0, NULL, NULL),
('Indonesia', NULL, '印尼', 'noun', 0, NULL, NULL),
('New Zealand', NULL, '紐西蘭', 'noun', 0, NULL, NULL),
('Ireland', NULL, '愛爾蘭', 'noun', 0, NULL, NULL),
('Scotland', NULL, '蘇格蘭', 'noun', 0, NULL, NULL),
('Wales', NULL, '威爾斯', 'noun', 0, NULL, NULL),
('Netherlands', NULL, '荷蘭', 'noun', 0, NULL, NULL),
('Belgium', NULL, '比利時', 'noun', 0, NULL, NULL),
('Switzerland', NULL, '瑞士', 'noun', 0, NULL, NULL),
('Austria', NULL, '奧地利', 'noun', 0, NULL, NULL),
('Poland', NULL, '波蘭', 'noun', 0, NULL, NULL),
('Czech Republic', NULL, '捷克', 'noun', 0, NULL, NULL),
('Slovakia', NULL, '斯洛伐克', 'noun', 0, NULL, NULL),
('Hungary', NULL, '匈牙利', 'noun', 0, NULL, NULL),
('Romania', NULL, '羅馬尼亞', 'noun', 0, NULL, NULL),
('Bulgaria', NULL, '保加利亞', 'noun', 0, NULL, NULL),
('Greece', NULL, '希臘', 'noun', 0, NULL, NULL),
('Turkey', NULL, '土耳其', 'noun', 0, NULL, NULL),
('Ukraine', NULL, '烏克蘭', 'noun', 0, NULL, NULL),
('Belarus', NULL, '白俄羅斯', 'noun', 0, NULL, NULL),
('Latvia', NULL, '拉脫維亞', 'noun', 0, NULL, NULL),
('Estonia', NULL, '愛沙尼亞', 'noun', 0, NULL, NULL),
('Lithuania', NULL, '立陶宛', 'noun', 0, NULL, NULL),
('Finland', NULL, '芬蘭', 'noun', 0, NULL, NULL),
('Norway', NULL, '挪威', 'noun', 0, NULL, NULL),
('Sweden', NULL, '瑞典', 'noun', 0, NULL, NULL),
('Denmark', NULL, '丹麥', 'noun', 0, NULL, NULL),
('Iceland', NULL, '冰島', 'noun', 0, NULL, NULL),
('Portugal', NULL, '葡萄牙', 'noun', 0, NULL, NULL),
('Luxembourg', NULL, '盧森堡', 'noun', 0, NULL, NULL),
('Monaco', NULL, '摩納哥', 'noun', 0, NULL, NULL),
('Vatican City', NULL, '梵蒂岡', 'noun', 0, NULL, NULL),
('San Marino', NULL, '聖馬利諾', 'noun', 0, NULL, NULL),
('Andorra', NULL, '安道爾', 'noun', 0, NULL, NULL),
('Liechtenstein', NULL, '列支敦斯登', 'noun', 0, NULL, NULL),
('Malta', NULL, '馬爾他', 'noun', 0, NULL, NULL),
('Cyprus', NULL, '塞普勒斯', 'noun', 0, NULL, NULL),
('Croatia', NULL, '克羅埃西亞', 'noun', 0, NULL, NULL),
('Slovenia', NULL, '斯洛維尼亞', 'noun', 0, NULL, NULL),
('Serbia', NULL, '塞爾維亞', 'noun', 0, NULL, NULL),
('Montenegro', NULL, '蒙特內哥羅', 'noun', 0, NULL, NULL),
('Bosnia and Herzegovina', NULL, '波士尼亞與赫塞哥維納', 'noun', 0, NULL, NULL),
('North Macedonia', NULL, '北馬其頓', 'noun', 0, NULL, NULL),
('Albania', NULL, '阿爾巴尼亞', 'noun', 0, NULL, NULL),
('Kosovo', NULL, '科索沃', 'noun', 0, NULL, NULL),
('Moldova', NULL, '摩爾多瓦', 'noun', 0, NULL, NULL),
('Georgia', NULL, '喬治亞', 'noun', 0, NULL, NULL),
('Armenia', NULL, '亞美尼亞', 'noun', 0, NULL, NULL),
('Azerbaijan', NULL, '亞塞拜然', 'noun', 0, NULL, NULL),
('Kazakhstan', NULL, '哈薩克', 'noun', 0, NULL, NULL),
('Uzbekistan', NULL, '烏茲別克', 'noun', 0, NULL, NULL),
('Turkmenistan', NULL, '土庫曼', 'noun', 0, NULL, NULL),
('Kyrgyzstan', NULL, '吉爾吉斯', 'noun', 0, NULL, NULL),
('Tajikistan', NULL, '塔吉克', 'noun', 0, NULL, NULL),
('Afghanistan', NULL, '阿富汗', 'noun', 0, NULL, NULL),
('Pakistan', NULL, '巴基斯坦', 'noun', 0, NULL, NULL),
('Bangladesh', NULL, '孟加拉', 'noun', 0, NULL, NULL),
('Sri Lanka', NULL, '斯里蘭卡', 'noun', 0, NULL, NULL),
('Nepal', NULL, '尼泊爾', 'noun', 0, NULL, NULL),
('Bhutan', NULL, '不丹', 'noun', 0, NULL, NULL),
('Myanmar', NULL, '緬甸', 'noun', 0, NULL, NULL),
('Laos', NULL, '寮國', 'noun', 0, NULL, NULL),
('Cambodia', NULL, '柬埔寨', 'noun', 0, NULL, NULL),
('Brunei', NULL, '汶萊', 'noun', 0, NULL, NULL),
('East Timor', NULL, '東帝汶', 'noun', 0, NULL, NULL),
('Mongolia', NULL, '蒙古', 'noun', 0, NULL, NULL),
('North Korea', NULL, '北韓', 'noun', 0, NULL, NULL),
('South Korea', NULL, '南韓', 'noun', 0, NULL, NULL),
('Taiwan', NULL, '台灣', 'noun', 0, NULL, NULL),
('Hong Kong', NULL, '香港', 'noun', 0, NULL, NULL),
('Macau', NULL, '澳門', 'noun', 0, NULL, NULL),
('Tibet', NULL, '西藏', 'noun', 0, NULL, NULL),
('Xinjiang', NULL, '新疆', 'noun', 0, NULL, NULL),
('Inner Mongolia', NULL, '內蒙古', 'noun', 0, NULL, NULL),
('Manchuria', NULL, '滿洲', 'noun', 0, NULL, NULL),
('Korea', NULL, '韓國', 'noun', 0, NULL, NULL),
('Japan', NULL, '日本', 'noun', 0, NULL, NULL),
('China', NULL, '中國', 'noun', 0, NULL, NULL),
('Taiwan', NULL, '台灣', 'noun', 0, NULL, NULL),
('Hong Kong', NULL, '香港', 'noun', 0, NULL, NULL),
('Macau', NULL, '澳門', 'noun', 0, NULL, NULL),
('Tibet', NULL, '西藏', 'noun', 0, NULL, NULL),
('Xinjiang', NULL, '新疆', 'noun', 0, NULL, NULL),
('Inner Mongolia', NULL, '內蒙古', 'noun', 0, NULL, NULL),
('Manchuria', NULL, '滿洲', 'noun', 0, NULL, NULL),

-- Furniture (noun) - all have plurals
('chair', 'chairs', '椅子', 'noun', 1, NULL, NULL),
('table', 'tables', '桌子', 'noun', 1, NULL, NULL),
('bed', 'beds', '床', 'noun', 1, NULL, NULL),
('desk', 'desks', '書桌', 'noun', 1, NULL, NULL),
('sofa', 'sofas', '沙發', 'noun', 1, NULL, NULL),
('lamp', 'lamps', '檯燈', 'noun', 1, NULL, NULL),
('bookshelf', 'bookshelves', '書架', 'noun', 1, NULL, NULL),
('wardrobe', 'wardrobes', '衣櫃', 'noun', 1, NULL, NULL),
('dresser', 'dressers', '梳妝台', 'noun', 1, NULL, NULL),
('nightstand', 'nightstands', '床頭櫃', 'noun', 1, NULL, NULL),
('coffee table', 'coffee tables', '茶几', 'noun', 1, NULL, NULL),
('dining table', 'dining tables', '餐桌', 'noun', 1, NULL, NULL),
('stool', 'stools', '凳子', 'noun', 1, NULL, NULL),
('bench', 'benches', '長凳', 'noun', 1, NULL, NULL),
('cabinet', 'cabinets', '櫃子', 'noun', 1, NULL, NULL),
('shelf', 'shelves', '架子', 'noun', 1, NULL, NULL),
('rack', 'racks', '掛架', 'noun', 1, NULL, NULL),
('mirror', 'mirrors', '鏡子', 'noun', 1, NULL, NULL),
('picture frame', 'picture frames', '相框', 'noun', 1, NULL, NULL),
('vase', 'vases', '花瓶', 'noun', 1, NULL, NULL),
('plant stand', 'plant stands', '花架', 'noun', 1, NULL, NULL),
('footstool', 'footstools', '腳凳', 'noun', 1, NULL, NULL),
('ottoman', 'ottomans', '腳凳', 'noun', 1, NULL, NULL),
('armchair', 'armchairs', '扶手椅', 'noun', 1, NULL, NULL),
('recliner', 'recliners', '躺椅', 'noun', 1, NULL, NULL),
('bean bag', 'bean bags', '豆袋椅', 'noun', 1, NULL, NULL),
('futon', 'futons', '日式沙發床', 'noun', 1, NULL, NULL),
('bunk bed', 'bunk beds', '上下舖', 'noun', 1, NULL, NULL),
('twin bed', 'twin beds', '單人床', 'noun', 1, NULL, NULL),
('queen bed', 'queen beds', '雙人床', 'noun', 1, NULL, NULL),
('king bed', 'king beds', '加大雙人床', 'noun', 1, NULL, NULL),
('crib', 'cribs', '嬰兒床', 'noun', 1, NULL, NULL),
('playpen', 'playpens', '遊戲圍欄', 'noun', 1, NULL, NULL),
('high chair', 'high chairs', '高腳椅', 'noun', 1, NULL, NULL),
('booster seat', 'booster seats', '增高墊', 'noun', 1, NULL, NULL),
('car seat', 'car seats', '汽車座椅', 'noun', 1, NULL, NULL),
('stroller', 'strollers', '嬰兒推車', 'noun', 1, NULL, NULL),
('baby carrier', 'baby carriers', '嬰兒背帶', 'noun', 1, NULL, NULL),
('baby swing', 'baby swings', '嬰兒搖椅', 'noun', 1, NULL, NULL),
('baby bouncer', 'baby bouncers', '嬰兒彈跳椅', 'noun', 1, NULL, NULL),
('baby walker', 'baby walkers', '嬰兒學步車', 'noun', 1, NULL, NULL),
('baby gym', 'baby gyms', '嬰兒健身架', 'noun', 1, NULL, NULL),
('baby mat', 'baby mats', '嬰兒墊', 'noun', 1, NULL, NULL),
('baby blanket', 'baby blankets', '嬰兒毯', 'noun', 1, NULL, NULL),
('baby pillow', 'baby pillows', '嬰兒枕頭', 'noun', 1, NULL, NULL),
('baby towel', 'baby towels', '嬰兒毛巾', 'noun', 1, NULL, NULL),
('baby bath', 'baby baths', '嬰兒浴盆', 'noun', 1, NULL, NULL),
('baby potty', 'baby potties', '嬰兒便盆', 'noun', 1, NULL, NULL),
('baby monitor', 'baby monitors', '嬰兒監視器', 'noun', 1, NULL, NULL),
('baby gate', 'baby gates', '嬰兒安全門', 'noun', 1, NULL, NULL),
('baby lock', 'baby locks', '嬰兒安全鎖', 'noun', 1, NULL, NULL),
('baby proofing', NULL, '嬰兒安全防護', 'noun', 0, NULL, NULL),

-- Toys (noun) - all have plurals
('doll', 'dolls', '娃娃', 'noun', 1, NULL, NULL),
('car', 'cars', '車子', 'noun', 1, NULL, NULL),
('ball', 'balls', '球', 'noun', 1, NULL, NULL),
('robot', 'robots', '機器人', 'noun', 1, NULL, NULL),
('puzzle', 'puzzles', '拼圖', 'noun', 1, NULL, NULL),
('teddy bear', 'teddy bears', '泰迪熊', 'noun', 1, NULL, NULL),

-- Drinks (noun) - some have plurals
('water', NULL, '水', 'noun', 0, NULL, NULL),
('milk', NULL, '牛奶', 'noun', 0, NULL, NULL),
('juice', NULL, '果汁', 'noun', 0, NULL, NULL),
('tea', NULL, '茶', 'noun', 0, NULL, NULL),
('coffee', NULL, '咖啡', 'noun', 0, NULL, NULL),
('soda', 'sodas', '汽水', 'noun', 1, NULL, NULL),
('hot chocolate', NULL, '熱巧克力', 'noun', 0, NULL, NULL),
('lemonade', NULL, '檸檬水', 'noun', 0, NULL, NULL),
('orange juice', NULL, '柳橙汁', 'noun', 0, NULL, NULL),
('apple juice', NULL, '蘋果汁', 'noun', 0, NULL, NULL),
('grape juice', NULL, '葡萄汁', 'noun', 0, NULL, NULL),
('coconut water', NULL, '椰子水', 'noun', 0, NULL, NULL),
('energy drink', 'energy drinks', '能量飲料', 'noun', 1, NULL, NULL),
('smoothie', 'smoothies', '冰沙', 'noun', 1, NULL, NULL),
('milkshake', 'milkshakes', '奶昔', 'noun', 1, NULL, NULL),
('hot tea', NULL, '熱茶', 'noun', 0, NULL, NULL),
('iced tea', NULL, '冰茶', 'noun', 0, NULL, NULL),
('hot coffee', NULL, '熱咖啡', 'noun', 0, NULL, NULL),
('iced coffee', NULL, '冰咖啡', 'noun', 0, NULL, NULL),
('hot milk', NULL, '熱牛奶', 'noun', 0, NULL, NULL),
('chocolate milk', NULL, '巧克力牛奶', 'noun', 0, NULL, NULL),
('strawberry milk', NULL, '草莓牛奶', 'noun', 0, NULL, NULL),
('banana milk', NULL, '香蕉牛奶', 'noun', 0, NULL, NULL),
('almond milk', NULL, '杏仁奶', 'noun', 0, NULL, NULL),
('soy milk', NULL, '豆漿', 'noun', 0, NULL, NULL),
('rice milk', NULL, '米漿', 'noun', 0, NULL, NULL),
('oat milk', NULL, '燕麥奶', 'noun', 0, NULL, NULL),
('bubble tea', NULL, '珍珠奶茶', 'noun', 0, NULL, NULL),
('green tea', NULL, '綠茶', 'noun', 0, NULL, NULL),
('black tea', NULL, '紅茶', 'noun', 0, NULL, NULL),
('herbal tea', NULL, '花草茶', 'noun', 0, NULL, NULL),
('chamomile tea', NULL, '洋甘菊茶', 'noun', 0, NULL, NULL),
('mint tea', NULL, '薄荷茶', 'noun', 0, NULL, NULL),
('ginger tea', NULL, '薑茶', 'noun', 0, NULL, NULL),
('honey tea', NULL, '蜂蜜茶', 'noun', 0, NULL, NULL),
('milk tea', NULL, '奶茶', 'noun', 0, NULL, NULL),
('fruit tea', NULL, '水果茶', 'noun', 0, NULL, NULL),
('iced coffee', NULL, '冰咖啡', 'noun', 0, NULL, NULL),
('espresso', NULL, '義式濃縮咖啡', 'noun', 0, NULL, NULL),
('cappuccino', NULL, '卡布奇諾', 'noun', 0, NULL, NULL),
('latte', NULL, '拿鐵', 'noun', 0, NULL, NULL),
('mocha', NULL, '摩卡', 'noun', 0, NULL, NULL),
('americano', NULL, '美式咖啡', 'noun', 0, NULL, NULL),
('macchiato', NULL, '瑪奇朵', 'noun', 0, NULL, NULL),
('frappuccino', NULL, '星冰樂', 'noun', 0, NULL, NULL),

-- Main Dishes (noun) - some have plurals
('rice', NULL, '飯', 'noun', 0, NULL, NULL),
('noodle', 'noodles', '麵條', 'noun', 1, NULL, NULL),
('soup', NULL, '湯', 'noun', 0, NULL, NULL),
('salad', 'salads', '沙拉', 'noun', 1, NULL, NULL),
('steak', 'steaks', '牛排', 'noun', 1, NULL, NULL),
('fish', 'fish', '魚', 'noun', 0, NULL, NULL),
('chicken', NULL, '雞肉', 'noun', 0, NULL, NULL),
('beef', NULL, '牛肉', 'noun', 0, NULL, NULL),
('pork', NULL, '豬肉', 'noun', 0, NULL, NULL),
('lamb', NULL, '羊肉', 'noun', 0, NULL, NULL),
('duck', 'ducks', '鴨肉', 'noun', 1, NULL, NULL),
('shrimp', 'shrimp', '蝦子', 'noun', 0, NULL, NULL),
('crab', 'crabs', '螃蟹', 'noun', 1, NULL, NULL),
('eggplant', 'eggplants', '茄子', 'noun', 1, NULL, NULL),
('tofu', NULL, '豆腐', 'noun', 0, NULL, NULL),
('pork chop', 'pork chops', '豬排', 'noun', 1, NULL, NULL),
('chicken wing', 'chicken wings', '雞翅', 'noun', 1, NULL, NULL),
('chicken leg', 'chicken legs', '雞腿', 'noun', 1, NULL, NULL),
('chicken breast', 'chicken breasts', '雞胸肉', 'noun', 1, NULL, NULL),
('beef stew', NULL, '燉牛肉', 'noun', 0, NULL, NULL),
('beef burger', 'beef burgers', '牛肉漢堡', 'noun', 1, NULL, NULL),
('beef noodle', 'beef noodles', '牛肉麵', 'noun', 1, NULL, NULL),
('beef curry', NULL, '牛肉咖哩', 'noun', 0, NULL, NULL),
('beef stir-fry', NULL, '炒牛肉', 'noun', 0, NULL, NULL),
('beef soup', NULL, '牛肉湯', 'noun', 0, NULL, NULL),
('beef salad', 'beef salads', '牛肉沙拉', 'noun', 1, NULL, NULL),
('beef sandwich', 'beef sandwiches', '牛肉三明治', 'noun', 1, NULL, NULL),
('beef taco', 'beef tacos', '牛肉塔可', 'noun', 1, NULL, NULL),
('beef burrito', 'beef burritos', '牛肉捲餅', 'noun', 1, NULL, NULL),
('beef pizza', 'beef pizzas', '牛肉披薩', 'noun', 1, NULL, NULL),
('beef pasta', NULL, '牛肉義大利麵', 'noun', 0, NULL, NULL),
('beef rice', NULL, '牛肉飯', 'noun', 0, NULL, NULL),
('beef noodle soup', NULL, '牛肉麵湯', 'noun', 0, NULL, NULL),
('beef curry rice', NULL, '牛肉咖哩飯', 'noun', 0, NULL, NULL),
('beef stir-fry rice', NULL, '炒牛肉飯', 'noun', 0, NULL, NULL),
('beef salad rice', NULL, '牛肉沙拉飯', 'noun', 0, NULL, NULL),
('beef sandwich rice', NULL, '牛肉三明治飯', 'noun', 0, NULL, NULL),
('beef taco rice', NULL, '牛肉塔可飯', 'noun', 0, NULL, NULL),
('beef burrito rice', NULL, '牛肉捲餅飯', 'noun', 0, NULL, NULL),
('beef pizza rice', NULL, '牛肉披薩飯', 'noun', 0, NULL, NULL),
('beef pasta rice', NULL, '牛肉義大利麵飯', 'noun', 0, NULL, NULL),

-- Bubble Tea Toppings (noun) - some have plurals
('pearl', 'pearls', '珍珠', 'noun', 1, NULL, NULL),
('jelly', 'jellies', '果凍', 'noun', 1, NULL, NULL),
('pudding', 'puddings', '布丁', 'noun', 1, NULL, NULL),
('red bean', 'red beans', '紅豆', 'noun', 1, NULL, NULL),
('taro', NULL, '芋頭', 'noun', 0, NULL, NULL);

-- ========================================
-- INDEXES FOR PERFORMANCE
-- ========================================

-- Original schema indexes
CREATE INDEX IF NOT EXISTS idx_admin_messages_created_at ON admin_messages(created_at);
CREATE INDEX IF NOT EXISTS idx_game_methods_grade ON game_methods(grade1, grade2, grade3, grade4, grade5, grade6);
CREATE INDEX IF NOT EXISTS idx_textbooks_grade ON textbooks(grade);
CREATE INDEX IF NOT EXISTS idx_units_textbook_id ON units(textbook_id);
CREATE INDEX IF NOT EXISTS idx_vocabulary_unit_id ON vocabulary(unit_id);

-- Learning content indexes
CREATE INDEX IF NOT EXISTS idx_sentence_patterns_grade_id ON sentence_patterns(grade_id);
CREATE INDEX IF NOT EXISTS idx_sentence_patterns_type ON sentence_patterns(pattern_type);
CREATE INDEX IF NOT EXISTS idx_question_answer_pairs_question ON question_answer_pairs(question_pattern_id);
CREATE INDEX IF NOT EXISTS idx_question_answer_pairs_answer ON question_answer_pairs(answer_pattern_id);
CREATE INDEX IF NOT EXISTS idx_words_part_of_speech ON words(part_of_speech);
CREATE INDEX IF NOT EXISTS idx_words_has_plural ON words(has_plural);
CREATE INDEX IF NOT EXISTS idx_word_theme_associations_word_id ON word_theme_associations(word_id);
CREATE INDEX IF NOT EXISTS idx_word_theme_associations_theme_id ON word_theme_associations(theme_id);
CREATE INDEX IF NOT EXISTS idx_pattern_slots_pattern_id ON pattern_slots(pattern_id);
